### ISSUE TITLE
Member constraints can't reference existentially quantified variables

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#107]
https://github.com/isovector/polysemy/issues/103#issuecomment-502027385 gives an example in which an existentially scoped type variable `s` is attempted to be used in the context of a `Member (State s) r` constraint.

[Trac #9223](https://gitlab.haskell.org/ghc/ghc/issues/9223) suggests that this is caused by `Member`'s use of `~`:

https://github.com/isovector/polysemy/blob/18e16f68db2ae77d54d23b18aafa1b82a4f64b0c/src/Polysemy/Internal/Union.hs#L105

This is more of a problem in GHC than in polysemy, though thankfully there is a workaround. If we introduce the `Member` constraint, and then existentialize afterwards, everything works. See https://github.com/isovector/polysemy/issues/103#issuecomment-502145910 for details.

**Comment by isovector** [comment]
It's probably worth opening a GHC bug for this.

**Comment by isovector** [comment]
Apparently section 5.2 of [https://www.microsoft.com/en-us/research/publication/outsideinx-modular-type-inference-with-local-assumptions/](OutsideIn) is good reading on this topic.

**Comment by incertia** [comment]
i'm not quite sure how to adapt the given workaround to the following code trying to abstract around input streams (sockets, stdin/out, files, websockets, etc)

```haskell
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}

module Main where

import Data.Function ((&))
import Polysemy
import System.IO

data Stream s m a where
  Recv :: Stream s m String
  Send :: String -> Stream s m ()
makeSem ''Stream

streamToIO :: forall s r a. (Member (Embed IO) r)
           => String
           -> (Sem (Stream s ': r) a)
           -> Sem r a
streamToIO name action = do
  interpret (embed @IO . \case
      Recv     -> putStr (name ++ "> ") >> getLine
      Send buf -> putStr (name ++ "> ") >> putStrLn buf
    ) action

multistream :: forall s1 s2 r. (Member (Stream s1) r, Member (Stream s2) r, Member (Embed IO) r)
            => Sem r ()
multistream = do
  a <- recv @s1
  b <- recv @s2
  embed . putStrLn $ "got " ++ a ++ " from A and " ++ b ++ " from B"
  send @s1 b
  send @s2 a

runStreamsIO :: forall s1 s2. IO ()
runStreamsIO =
  runFinal $ embedToFinal @IO
           $ streamToIO @s2 "B"
           $ streamToIO @s1 "A"
           $ multistream

main :: IO ()
main = do
  hSetBuffering stdout NoBuffering
  hSetBuffering stdin  LineBuffering
  runStreamsIO
```

compiling without the plugin throws an error about an unhandled `Stream` effect and compiling with the plugin produces an incorrect result.

```
A> A
A> B
got A from A and B from B
A> B
A> A
```

the expected result would be

```
A> A
B> B
got A from A and B from B
A> B
B> A
```

perhaps the plugin collapsed `forall s1 s2` into a single variable with the first call to `streamToIO`?

**Comment by incertia** [comment]
turns out i can just give concrete types to make this work

```haskell
data StreamA
data StreamB

main :: IO ()
main = do
  hSetBuffering stdout NoBuffering
  hSetBuffering stdin  LineBuffering
  runFinal $ embedToFinal @IO
           $ streamToIO @StreamB "B"
           $ streamToIO @StreamA "A"
           $ multistream @StreamA @StreamB
```

```
A> A
B> B
got A from A and B from B
A> B
B> A
```

**Comment by googleson78** [comment]
Note:
The original issue that @incertia had was that it seems the instance resolution algorithm doesn't consider `s1` and `s2` to be different - and rightfully so (?) because you could instantiate them to the same thing.
<details><summary>From his code, but slightly modified to have explicit applications on `multistream`</summary>

```
polysemy       >     • Overlapping instances for Polysemy.Internal.Union.Find
polysemy       >                                   (Stream s1) '[Stream s2, Stream s1, Embed IO]
polysemy       >         arising from a use of ‘multistream’
polysemy       >       Matching instances:
polysemy       >         instance [safe] forall a (t :: a) (z :: [a]) (_1 :: a).
polysemy       >                         Polysemy.Internal.Union.Find t z =>
polysemy       >                         Polysemy.Internal.Union.Find t (_1 : z)
polysemy       >           -- Defined at src/Polysemy/Internal/Union.hs:217:10
polysemy       >         instance [overlapping] [safe] forall a (t :: a) (z :: [a]).
polysemy       >                                       Polysemy.Internal.Union.Find t (t : z)
polysemy       >           -- Defined at src/Polysemy/Internal/Union.hs:213:30
polysemy       >       (The choice depends on the instantiation of ‘s2, k, s1, k1’
polysemy       >        To pick the first instance above, use IncoherentInstances
polysemy       >        when compiling the other instance declarations)
polysemy       >     • In the second argument of ‘($)’, namely ‘multistream @s1 @s2’
polysemy       >       In the second argument of ‘($)’, namely
polysemy       >         ‘streamToIO @s2 "B" $ multistream @s1 @s2’
polysemy       >       In the second argument of ‘($)’, namely
polysemy       >         ‘streamToIO @s1 "A" $ streamToIO @s2 "B" $ multistream @s1 @s2’
polysemy       >    |
polysemy       > 47 |   multistream @s1 @s2
```
</details>

(not sure about this) "Intuitively" the issue should be that type variables don't carry any information on them (no dicts or something) to disambiguate at run-time between `s1` and `s2`, so the `ghc` doesn't know which dict for `Find` to put in there while compiling.
