### ISSUE TITLE
Custom error messages seem to be actively harmful

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#108]
There are a lot of issues caused by the error messages being unhelpful. See https://github.com/isovector/polysemy/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22custom+errors%22+ for a list of the ones that have been reported.

In many cases, these error messages are being emitted _instead_ of the usual GHC ones; which are often good enough to correctly diagnose the problem.

One particularly bad example is when an interpreter is run with the wrong arity. GHC will say "maybe you forgot to apply some arguments?", but polysemy will say "AMBIGUOUS EFFECT". 

Maybe there's a good way of scoping down the circumstances in which the errors can occur. In the above example, possibly we could have a type family match on `a -> SomeEffect` that detects when the arity is wrong. 

In https://github.com/isovector/polysemy/issues/74#issuecomment-502052820 , @TheMatten and @kcsongor give a typefamily that can detect when the row effect is polymorphic, which we can probably use to avoid the "ambiguous effect" error messages when running interpreters (when the row won't be polymorphic).

**Comment by isovector** [comment]
I've opened https://github.com/CRogers/should-not-typecheck/pull/15, which will add support to `should-not-typecheck` to allow us to write tests against the custom error messages. Once that lands in hackage, I'll start writing tests in `polysemy` to see where the error messages are falling down, and then see about fixing them.

**Comment by isovector** [comment]
Fuck --- custom type errors don't show up via `-fdefer-type-errors`. https://gitlab.haskell.org/ghc/ghc/issues/16249. This means we can't test them.

**Comment by isovector** [comment]
I wonder if we can observe these with a plugin...

**Comment by isovector** [comment]
Nope; type errors explode before the TC plugin can run.

**Comment by isovector** [comment]
I'm quickly losing my will to live trying to test these. I was halfway through writing a bash script that will run `stack runghc` on files and then do bash things to compare them to known outputs....

But then I had a better idea which is to just rip all of these things out. If someone cares, they're welcome to give it a go, but otherwise I'm going to start the excising!

**Comment by kcsongor** [comment]
I might be misunderstanding what you want to do with the errors, but FWIW I use doctests to test them; see here for example: https://github.com/kcsongor/generic-lens/blob/master/src/Data/Generics/Product/Fields.hs#L107

**Comment by isovector** [comment]
@kcsongor i love you with the fire of a thousand suns
