### ISSUE TITLE
Documentation for the difference in semantics on when you run your effects

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#127]
What is the difference between `runState . runError` and `runError . runState`? When is `runResourceBase` safe? The answers to all of these questions and more. COMING THIS SUMMER

**Comment by isovector** [comment]
I'm feeling burned out on polysemy. Anyone interested in tackling this, or should we just push v1 without it?

**Comment by TheMatten** [comment]
Would simple comments like "run before X to get Y behaviour, run after X to get Z behaviour" in docs of corresponding functions be sufficient enough?

**Comment by isovector** [comment]
Probably. I'd put it in the haddock for `Sem`.
