### ISSUE TITLE
Crappy error message

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#136]
```haskell
existsKV :: Member (KVStore k v) r => k -> Sem r Bool
existsKV = isJust . lookupKV
```

should be

```haskell
existsKV :: Member (KVStore k v) r => k -> Sem r Bool
existsKV = fmap isJust . lookupKV
```

but produces this lame ass error:

```
    • Ambiguous use of effect 'KVStore'
      Possible fix:
        add (Member (KVStore k v0) r0) to the context of 
          the type signature
      If you already have the constraint you want, instead
        add a type application to specify
          'k', and 'v0' directly, or activate polysemy-plugin which
            can usually infer the type correctly.
    • In the second argument of ‘(.)’, namely ‘lookupKV’
      In the expression: isJust . lookupKV
      In an equation for ‘existsKV’: existsKV = isJust . lookupKV
```

**Comment by adamConnerSax** [comment]
In my experience this happens all the time. As soon as something, anything, goes wrong, the unification of the r seems to fail and we get a Polysemy error.

**Comment by isovector** [comment]
@adamConnerSax yeah, it's terrible. Please report any easy-to-repro cases you can --- having lots of data points is what makes this easy to fix.

**Comment by adamConnerSax** [comment]
I will. But right now it happens in the midst of refactoring a huge monster of a data-science thing that is not helpful to look at.
But my impression is that it’s sort of an eager error, it’s the message I get when calling a function returning “Sem r a” with the wrong number of arguments or wrong types. This is exacerbated by my using ghcid so I’m always looking at the first error. Sometimes something more helpful is further down.

**Comment by isovector** [comment]
Yeah! Everything you've said here matches my experiences too. Let's get around to making it less frustrating for everyone.

There's some good news on this front. #88 and #106 are two cases in which we've lazy-fied the error messages. So there's hope!
