### ISSUE TITLE
UX around Lift

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#142]
Let's move `Lift` into `Polysemy.Lift.Type`, and then put `runLift` into `Polysemy.Lift`.

https://github.com/polysemy-research/polysemy-zoo/pull/33#issuecomment-506958946
https://github.com/polysemy-research/polysemy-zoo/pull/33#issuecomment-506968371

**Comment by googleson78** [comment]
I'll take a look at this in the weekend if nobody else is.
