### ISSUE TITLE
TH generates signatures with ambiguously-looking names

### ISSUE THREAD

**Issue by TheMatten** [polysemy-research/polysemy#157]
See https://www.stackage.org/haddock/nightly-2019-07-04/polysemy-0.5.1.0/Polysemy-Resource.html#v:bracket - it looks like `a` appears twice in `forall` - in reality, these are different variables (https://www.stackage.org/nightly-2019-07-04/hoogle?q=bracket+%2Bpolysemy) - `th-abstraction` defaults to names from type constructors instead of data constructors - so `b` in:
```hs
data Resource m a where
  Bracket :: m a -> (a -> m c) -> (a -> m b) -> Resource m b
```
is provided under name `a` - but `a` from `Resource m a`, not from `Bracket`!

While this shouldn't affect any functionality, it's puzzling to the user = bad UX.

**Comment by isovector** [comment]
This actually bites in lots of places -- eg `get` in `State`! I'm going to say this is probably our highest priority thing right now. @TheMatten do you have bandwidth to tackle it?
