### ISSUE TITLE
Loopbreaker dependency breaks haddock generation

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#160]
Haddock can't run plugins in 8.6 (https://github.com/haskell/haddock/issues/900 again). We can fix this by doing a 

```haskell
#ifndef __HADDOCK__
{-# OPTIONS_GHC -fplugin=Loopbreaker #-}
#endif
```

on a per module basis, but it'd be nice if we could figure out a way to conditionally enable it on a project-wide basis iff haddock isn't being run.

**Comment by isovector** [comment]
This doesn't seem to be solvable today, short of the ugly solution above. Which isn't going to happen.

So instead I suggest we make a new cabal flag: `--make-it-go-fast` which we guard the `Loopbreaker` on. That thing should be opt-in, so that hackage doesn't die. [I've pestered the haddock guys](https://github.com/haskell/haddock/pull/983#issuecomment-508950681) to release the fix, after which we can deprecate the `--make-it-go-fast` flag.

It's annoying, but probably the best we can do here :(

**Comment by isovector** [comment]
On the other hand, our actual speed bottleneck is [!668](https://gitlab.haskell.org/ghc/ghc/merge_requests/668), and will be until GHC 8.10. So I don't think anyone would notice the speed increases of `Loopbreaker` until then. And hopefully haddock will be fixed then too?

Let's just chop out `Loopbreaker` as a dependency for now. We know it works, and can just re-enable when all the upstream problems are sorted out.

**Comment by TheMatten** [comment]
Ok - users really shoudn't care about this stuff.
