### ISSUE TITLE
Missing interpreters

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#165]
Still need:

* `runMonadicOutput`
* `runOuputAsAnother` -- maybe more generally we want variance relations over our effects??

**Comment by googleson78** [comment]
What are the desired type signatures for these?

**Comment by isovector** [comment]
* `Member (Lift m) r => (o -> m ()) -> Sem (Output o ': r) a -> Sem r a`
* `Member (Output o2) r => (o1 -> o2) -> Sem (Output o1 ': r) a -> Sem r a`

**Comment by googleson78** [comment]
I'll add these around this coming weekend, if nobody else wants to before then.

W.r.t. the variance relations - most of the transformations should be something like (contra-)functors, but I don't immediately see how effects can fit the default `Functor` and `Contravariant`. Perhaps a special version for effects of these? Or just straight up writing all the `runXAsAnother` functions, without being too fancy (avoids increasing library surface area).

**Comment by isovector** [comment]
Back in the long long ago, @shlevy and I wrote this https://github.com/IxpertaSolutions/freer-effects/pull/32 --- essentially new type classes for co/contra/invariant functors over effects. The idea didn't get any use in reality, but I still think it was a nice solution.

**Comment by isovector** [comment]
Let's coordinate against #168 before putting in the engineering legwork --- I'd feel bad if I gave you the renaming runaround on two PRs in a row!
