### ISSUE TITLE
Come up with a consistent naming scheme

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#168]
I'm bad at naming things. Consider that these things all reference `IO`, but all have completely different semantics going on.

* `runIO`
* `runTraceIO`
* `runAsyncInIO`
* `runStateInIORef`

And then consider the `Resource` functions:

* `runResourceInIO`
* `runResource`
* `runResourceBase`

??????

and then `Output` is all over the place too:

* `runOutputAsList`
* `runFoldMapOutput`
* `runBatchOutput`

**Comment by isovector** [comment]
I think maybe `interpret`s should be "`run*`", but then `intercept`s should be something else. Maybe "`transform`" or something?

**Comment by isovector** [comment]
It would be good if the operators that work with `.@` all have their own naming scheme. Currently this is `*InIO` but that isn't very descriptive.

**Comment by isovector** [comment]
It seems like there are a few distinct categories of sem transformations here:

1. Things that implement one effect in terms of another, eg `runTraceIO`, `runOutputAsWriter`
2. Things that lower directly to IO, eg `runResourceInIO`, `runAsyncInIO`
3. Things that are functors over their effects, eg `runErrorAsAnther`, `runStateAsAnother`
4. Pure implementations, eg. `runResource` , `runOutputAsList`
5. Void implementations, eg. `runIgnoringTrace`, `runIgnoringOutput`
6. Transforming intercepts, eg `runBatchOutput` (I can't think of any others, but probably there are lots to be written!)

Presumably each group should have a naming convention

**Comment by TheMatten** [comment]
Some ideas:
1. `run_As_`
2. `run_In_`
3. `convert_`/`transform_`/`map_` or maybe even typeclass with e.g. `emap`?
4. They're both pure, but second is somewhat specific in return value - maybe `run_` and `run_To_`
5. `ignore_`
6. `runOutputAsBatching`?

**Comment by googleson78** [comment]
Regarding 5.: 

Is it possible to implement
```
ignore :: Sem (_ ': r) a -> Sem r a
```
🤔

**Comment by TheMatten** [comment]
We would somehow need to "catch" `x` in effect `e m x` - some sort of `e m x -> x` or proof that `x` is `()` (as is technically case with `Output`).

**Comment by TheMatten** [comment]
Basically, you can't come up with result value of action out of thin air, unless it's a singleton - `()`s are fine, but what about:
```hs
do val <- input @Int
   pure $ val + 1
```
What should happen when we ignore `Input`?...

**Comment by isovector** [comment]
It's impossible to ignore effects in general! Only in the case where all of your actions return `()`, or some other `Pointed` value.

**Comment by ocharles** [comment]
While you are considering naming, how tied to Srm are you? In my work, I've got ended up just calling it `Program`

**Comment by isovector** [comment]
I could be persuaded on changing `Sem`. But I like it because it's short, and reminds you of the package name.

**Comment by ocharles** [comment]
I just feel it's the kind of thing that people stumble over when they are actually talking about `polysemy`, and Haskell could do with few seemingly random terms, imo.

**Comment by jhenahan** [comment]
Personally, I'd lean toward something to the effect of: `run<Effect><Stuff>` (and maybe `run<Effect>As<Stuff>` for the functor case), with pure interpreters just being `run<Effect>`; `ignore<Effect>`; for the explicit lowering from a `Lift m`, maybe `lower<Effect><Monad>`, for the sake of explicitness.
