### ISSUE TITLE
How to interpret recursive effects?

### ISSUE THREAD

**Issue by blaisepascal** [polysemy-research/polysemy#176]
How do you write a `runFoo :: Sem (Foo ': r) a -> Sem r a` with recursive actions?
I am trying to write a Lambda Calculus evaluater (a la Write You A Haskell), and I have an `Eval` effect with an interpreter that looks like:

```
runEval :: Member (Writer [Step]) r => Sem (Eval ': r) a -> Sem r a
runEval = interpret $ \case
  Eval env expr -> case expr of
    Lit (LInt x) -> return $ VInt (fromIntegral x)
    Lit (LBool x) -> return $ VBool x
    Var x -> do
      return $ env Map.! x
    Lam x body ->  return (VClosure x body env)
    App a b ->  do
      x <- eval env a
      y <- eval env b
      apply' x y
  Apply f x -> do
    let (Vclosure y body env) = f
    eval (extend env y x) body
```
It works as expected when I pull the bodies of the `Eval` and `Apply` into their own functions that call each other, rather than try to use them as effects. But done this way I get compiler complaints about an unhandled `Eval` effect. This is reasonable, since the type of `runEval` has to be modified to say that `Eval` is a member of `r`, so the list of types must have an infinite number of `Evals` in it.

I know one valid answer to "how to do this" is "don't do this", but I'm curious as to if it can be done.

**Comment by isovector** [comment]
Can you post the full example? It's hard to get a sense of what's going on without it!

**Comment by blaisepascal** [comment]
Sure.

I get a compile error of `Unhandled effect 'Eval'` in the definition of `runEval`. I can see that `runEvalRecursively` requires `Eval` to be a member of `r`, so it never completely removes `Eval` from the list of effects.

With `runEval'` and `runEvalFunctionally`, everything works fine. The evaluation functions `eval'` and `apply'` are mutually recursive, but they aren't actions of the `Eval` event. 

```
{-# LANGUAGE TemplateHaskell #-}

-- |

module Untyped.EvalSem
  ( runEval
  , Step
  , Value
  ) where

import           Polysemy
import           Polysemy.State
import           Polysemy.Writer

import           Data.Function
import qualified Data.Map        as Map

import           Untyped.Syntax (Expr(..), Lit(..))
-- data Expr = Lit Lit | Var String | Lam String Expr | App Expr Expr
-- data Lit = LInt Int | LBool Bool

type Step = (Int, Expr)
type Scope = Map.Map String Value

emptyScope :: Scope
emptyScope = Map.empty

extend :: Scope -> String -> Value -> Scope
extend env v t = Map.insert v t env

data Value
  = VInt Integer
  | VBool Bool
  | VClosure String Expr (Scope)

data Eval m a where
  Red :: Expr -> Eval m ()
  Eval :: Scope -> Expr -> Eval m Value
  Apply :: Value -> Value -> Eval m Value

makeSem ''Eval

runEvalRecursively :: Members [Eval, Writer [Step]] r => Sem (Eval ': r) a -> Sem r a
runEvalRecursively = interpret $ \case
  Eval env expr -> do
    red expr
    case expr of
      Lit (LInt x) -> return $ VInt (fromIntegral x)
      Lit (LBool x) -> return $ VBool x
      Var x -> do
        return $ env Map.! x
      Lam x body ->  return (VClosure x body env)
      App a b ->  do
        x <- eval env a
        y <- eval env b
        apply x y
  Red expr -> tell [(0 :: Int, expr)]
  Apply a b  -> do
    let (VClosure n body env') = a
    eval (extend env' n b) body

-- Doesn't work
runEval :: Expr -> ([Step],Value)
runEval ex = run $  runWriter $ runEvalRecursively (eval emptyScope ex)

runEvalFunctionally :: Member (Writer [Step]) r => Sem (Eval ': r) a -> Sem r a
runEvalFunctionally = interpret $ \case
  Eval scope ex -> eval' scope ex
  Red expr -> red' expr
  Apply f x -> apply' f x

eval' :: Member (Writer [Step]) r => Scope -> Expr -> Sem r Value
eval' env expr = do
  red' expr
  case expr of
    Lit (LInt x) -> return $ VInt (fromIntegral x)
    Lit (LBool x) -> return $ VBool x
    Var x -> do
      return $ env Map.! x
    Lam x body ->  return (VClosure x body env)
    App a b ->  do
      x <- eval' env a
      y <- eval' env b
      apply' x y

red' :: Member (Writer [Step]) r
     => Expr -> Sem r ()
red' x =  tell [(0 :: Int,x)]

apply' :: Member (Writer [Step]) r => Value -> Value -> Sem r Value
apply' (VClosure n body env') ex = do
  eval' (extend env' n ex) body
apply' _ _ = error "Tried to apply non-closure"

-- Works
runEval' :: Expr -> ([Step],Value)
runEval' ex = run $ runWriter $ runEvalFunctionally (eval emptyScope ex)

```

**Comment by TheMatten** [comment]
@isovector maybe some short of interpreter:
```hs
exhaust :: (forall m x. e m a -> Either (Sem (e:r) a) (Sem r a)) -> Sem (e:r) a -> Sem r a
```
which would sequence `(e:r)` actions until it gets resulting `r` action?
User would then put recursive cases into `Left` and base ones into `Right`.

**Comment by adamConnerSax** [comment]
Off-Topic: 
That sounds a little like an anamorphism (```unfold```). 
Is ```Several``` in the zoo a fold?

**Comment by ocharles** [comment]
`runEvalRecursively :: Members [Eval, Writer [Step]] r => Sem (Eval ': r) a -> Sem r a` is pretty weird though. From your definition, you're basically saying "I want to handle the 'outermost' part of an `Expr`, and then some other interpretation will apply to any remaining `Expr`s". It seems very strange to want to allow differing interpretations for an `Expr` depending on where it occurs.

I think the correct type is just `runEvalRecursively :: Members [Writer [Step]] r => Sem (Eval ': r) a -> Sem r a`, and then you would have a locally scoped recursive function of the type `go :: Expr -> Sem r a`. This is exactly what your `runEvalFunctionally` approach is doing, and imo it's the correct way to do this.

**Comment by blaisepascal** [comment]
I think what I want to say is "In certain situations, I want to interpret an action in terms of other actions." I agree that `runEvalRecursively :: Members [Eval, Writer [Step]] r => Sem (Eval ': r) a -> sem r a` is weird. In my mind it seems to suggest that the `r` has infinitely many `Eval` in it.

The "I want to interpret an action in terms of other actions" suggest a possible solution:
```
runFooRecursively :: Member ((Writer [String]), Show a => Sem (Eval ': r) a -> Sem r a
runFooRecursively = interpret $ \case
  Foo x = do
    tell "Foo" ++ show x
    return x
  Bar x = do
    tell "Bar" ++ show x
    return x
  FooBar x = runFooRecursively $ do 
    foo x
    bar x
```
This seems to work.

The other solution that comes to mind is a trivial
```
runEvalTrivial :: Sem (Eval ': r) a -> Sem r a
runEvalTrivial x = do
  out <- x
  return x
```
and then call it as `(run . runWriter . runEvalTrivial . runEvalRecursively) (eval emptyScope ex)`

I don't know offhand if `runEvalTrivial` will actually do what I want, though. It's using two interpreters for the same effect in the stack, and I don't know which Polysemy will use for the general case.

**Comment by isovector** [comment]
This fell off my radar; sorry. Is it still an issue, or is it OK to close?

**Comment by blaisepascal** [comment]
I think it's OK to close. I got the results I wanted, and I'm satisfied that while this may be a good thing in some cases, I'm not really using effects effectively in this problem.
