### ISSUE TITLE
Would it be a good idea to use `type-errors-pretty` to write text of error messages?

### ISSUE THREAD

**Issue by chshersh** [polysemy-research/polysemy#180]
I've [announced the `type-errors-pretty` library](https://twitter.com/ChShersh/status/1150707729658286080) recently. And I wonder, would it improve code readability and maintainability if it will be used instead of default `ErrorMessage`? I see that `polysemy` has a lot of custom type errors, so I wonder, whether the library with a lot of custom error messages can benefit from prettier way of defining the text of those messages.

For example, instead of existing:

```haskell
type AmbigousEffectMessage (rstate :: EffectRowCtor)
                           (r :: EffectRow)
                           (e :: k)
                           (t :: Effect)
                           (vs :: [Type]) =
        ( 'Text "Ambiguous use of effect '"
    ':<>: 'ShowType e
    ':<>: 'Text "'"
    ':$$: 'Text "Possible fix:"
    ':$$: 'Text "  add (Member ("
    ':<>: 'ShowType t
    ':<>: 'Text ") "
    ':<>: ShowRQuoted rstate r
    ':<>: 'Text ") to the context of "
    ':$$: 'Text "    the type signature"
    ':$$: 'Text "If you already have the constraint you want, instead"
    ':$$: 'Text "  add a type application to specify"
    ':$$: 'Text "    "
    ':<>: PrettyPrintList vs
    ':<>: 'Text " directly, or activate polysemy-plugin which"
    ':$$: 'Text "      can usually infer the type correctly."
        )
```

This can look like this using `type-errors-pretty` library:

```haskell
type AmbigousEffectMessage (rstate :: EffectRowCtor)
                           (r :: EffectRow)
                           (e :: k)
                           (t :: Effect)
                           (vs :: [Type])
    = "Ambiguous use of effect '" <> e <> "'"
    % "Possible fix:"
    % "  add (Member (" <> t <> ") " <> ShowRQuoted rstate r <> ") to the context of "
    % "    the type signature"
    % "If you already have the constraint you want, instead"
    % "  add a type application to specify"
    % "    " <> PrettyPrintList vs <> " directly, or activate polysemy-plugin which"
    % "      can usually infer the type correctly."
```

**Comment by isovector** [comment]
I'd accept a PR! Also how would you feel about combining forces with `type-errors` into one super type error package?

**Comment by chshersh** [comment]
I don't know about single super type error package. I'm usually concerned about the number of dependencies in my packages. `type-errors` doesn't have many dependencies, but still has some except `base`. Usually, when I write type errors, I need to specify only the text of the message. I don't need Template Haskell solutions for substitutions and `IfStuck` capabilities. So my strategy usually is the following:

1. Only a couple of error messages: use `ErrorMessage`
2. A lot of error messages: use `type-errors-pretty`.
3. Previous point + you need advanced logic for producing type errors: use `type-errors` + `type-errors-pretty`.

In the end, it's all about tradeoffs: whether the benefits of using a package are worth (or maybe it's just not possible to do something without external library) adding an extra dependency.
