### ISSUE TITLE
'LastMember' vs 'prj'

### ISSUE THREAD

**Issue by KingoftheHomeless** [polysemy-research/polysemy#183]
`LastMember` is currently used in `runViaForklift` to identify individual uses of `embed` and interpret these in the forked thread rather than shipping them off to the interpreter thread.
However, there already exists a mechanism to identify if an union corresponds to a specific effect: namely, `prj` in `Polysemy.Internal.Union`. Indeed, it's possible to use `prj` in place of `decompLast`.

What benefit does `LastMember` bring compared to `prj`?

**Comment by KingoftheHomeless** [comment]
@isovector I'm still curious about this. See https://github.com/KingoftheHomeless/polysemy/tree/Forklift for a version of polysemy without `LastMember`.

**Comment by isovector** [comment]
I think you're right about this. I wrote `prj` because I could, but never found a use case for it. Then when I had one, I wrote `LastMember` instead! If everything works without it I'm happy to get rid of it!

**Comment by isovector** [comment]
I think you're right about this. I wrote `prj` because I could, but never found a use case for it. Then when I had one, I wrote `LastMember` instead! If everything works without it I'm happy to get rid of it!

**Comment by KingoftheHomeless** [comment]
I'll open a pull request. Hold on.
