### ISSUE TITLE
Backing up performance claims

### ISSUE THREAD

**Issue by Infinisil** [polysemy-research/polysemy#184]
I think any library that claims to be fast should also back up that claim. The Readme mentions "zero-cost" and "35x faster than freer-simple" without any link to any measurements. There is https://gist.github.com/isovector/e4832512ec9c73bff94432a7a58470f9 you linked to previously, which has some results at least, but isn't very clear or convincing.

If I understand correctly, the big performance benefits only come with a very recent GHC (>=8.9), one that includes https://gitlab.haskell.org/ghc/ghc/merge_requests/668. This would means everybody using it won't actually be getting good performance for a while, which also means people can't easily verify that claim on their own.

I think this should really be addressed before the 1.0 release. Ideally this would include:
- A mention of which GHC version you need to get the best performance.
- A benchmark that compares different effect libraries
- A set of precise instructions how the best performance can be achieved. This might include a mention of `INLINABLE`/`INLINE`, the necessary GHC flags and the optimization level

**Comment by Avi-D-coder** [comment]
I would love to see [effect-benchmarks](https://github.com/patrickt/effects-benchmarks) run with ghc-8.10 and up to date polysemy.

**Comment by isovector** [comment]
Issues like these make me want to stop doing open source.

I'm really, *really* tired of having this argument. I spent two months of my life bashing my head against the performance here. I patched the compiler. I wrote a plugin to do custom optimization passes for you. I have done everything in my power on this issue; whether or not you believe me on that is up to you.

If the performance really and truly is a deal-breaker for you, then please verify the results for yourself. I will happily publish your findings, and if they're not as good as I claim, then I will work with you to solve that. I will happily merge PRs that address your points.

If you're not convinced, and don't want to do this work, then you are under no obligation to use polysemy. I won't take it personally if you label it "too experimental" for your needs. But I've done my part on this. If it's really a concern for you, please do yours.

**Comment by Avi-D-coder** [comment]
Fair enough, I'll try to build ghc-8.10 and update effect-benchmarks in the next few weeks.

**Comment by Infinisil** [comment]
Sorry for my tone, I was a bit stingy yesterday. I really appreciate you for taking time to optimize this, developing polysemy and working on open-source in general. Maybe I should mention how I came to write this issue:

While using polysemy for [a project](https://github.com/infinisil/arvy), I noticed that when running with profiling, most of the time was taken up by polysemy. This wasn't a big surprise, I knew about this needing a very recent GHC for it to get the best out of it. So I spent 2 days or so to [updating ghcHead](https://github.com/NixOS/nixpkgs/pull/63001) for Nix, [patching](https://github.com/Infinisil/arvy/blob/ghcHEAD/default.nix) [dependencies](https://github.com/polysemy-research/polysemy/issues/99) so they would compile, and finally running my program again. But it turned out that the performance was about the same, which I now think was due to some GHC flag I missed. That plus the amount of work needed (now and in the future) to get dependencies working didn't seem worthwhile, so I stopped there.

Now maybe I should've continued there, but honestly, I don't even know if I'm on the right track. Am I inlining enough for it to do the optimizations? Do I need to use `polysemy-plugin` to get good performance? What GHC options do I need? What optimization level? Can I profile this correctly with `-prof` or does that prevent getting accurate results? I'm very new to any kind of performance optimization in Haskell, and I'm probably not the only one.

So it's not that I don't believe in you having achieved zero-cost performance, but rather that it's very unclear how to get that performance, especially if one doesn't happen to know about the GHC MR and the blog post discussions elsewhere on the internet. (There is however also the [Sagan standard](https://en.wikipedia.org/wiki/Sagan_standard) as a valid but provoking reason one might open such an issue).

A small Readme section on performance explaining this would be enough. And if `effect-benchmarks` could be updated and then linked to from here that would be even better (thanks for mentioning this @Avi-D-coder). I'm willing to help out with getting a GHC 8.9/10 working with it, which can be automated rather well with Nix. I also have all these [patches for libraries](https://github.com/Infinisil/arvy/blob/ghcHEAD/default.nix) which should prove useful.

**Comment by isovector** [comment]
Thanks @Infinisil for the context --- I was a little grumpy myself yesterday.

There's an included benchmark, though it's not 100% up to date. It's going to need `-fplugin=Polysemy.Plugin` turned on in the benchmark suite, and then be compiled at `-O2`. It's a simple benchmark, but shows that fusion is possible in polysemy. It runs polysemy (called "discount") against mtl and freer-simple, and so should give you some info right off the bat. I expect mtl and polysemy to run at the same speed in this benchmark; they did when I finished my GHC patch, and if they don't now it's 95% likely to be caused by something stupid on my part.

To be explicit, the stars need to be aligned in the following way for polysemy to be optimized away:

* GHC 8.9+
* The module you want to be optimized needs to have `Polysemy.Internal` somewhere in its dependency tree
* `-O` or `-O2`
* `-fplugin=Polysemy.Plugin` 
* `-flate-specialise` (this should be automatically turned on by the plugin, but it's worth mentioning)
* additional core passes (also turned on by the plugin)
