### ISSUE TITLE
`raise` an arbitrary number of times

### ISSUE THREAD

**Issue by jgrosso** [polysemy-research/polysemy#188]
Is there a way to call one action inside another, if the called action has only a subset of the caller's effects? For example, something with type `foo :: (Members subset superset) => Sem subset () -> Sem superset ()`.

The following fails to compile, since (obviously) `subset ~ superset` is not true:

```
foo :: (Members subset superset) => Sem subset () -> Sem superset ()
foo = id
-- Could not deduce: subset ~ superset from the context...
```

and the following also doesn't typecheck because AFAICT `raise` is too concrete, requiring something of the form `eff ': subset`:

```
foo :: (Members subset superset) => Sem subset () -> Sem superset ()
foo = raise . id
-- Could not deduce: superset ~ (a : subset) from the context...
```

If worse comes to worse, I can make all my types concrete and use `raise` as many times as necessary, but I'm hoping there's a solution that doesn't require such premature specialization.

Thanks!

**Comment by TheMatten** [comment]
Usually we only make list of effects (partially) concrete in signatures of interpreters - by describing all effects action needs through `Member`(`s`) in it's signature, you're able to use it in any `Sem` that contains them "for free".

**Comment by jgrosso** [comment]
@TheMattern Thanks for the response! That's what I was thinking too, so I'm a bit confused why my second code example doesn't compile (since it initially seems to me that it _should_ be available for free in this case).

**Comment by TheMatten** [comment]
`raise . id` does what error says - `id` preserves both type and value while `raise` extends `subset` with arbitrary `a`. Really, there should be no point in implementing this function - make use of `Members effs r` over `Sem r a`, where `r` is a type variable.

**Comment by jgrosso** [comment]
@TheMatten Ohh, so you're saying that it should really be of the form

```
foo :: (Members subset openSubset, Members subset superset) => Sem openSubset a -> Sem superset a
```

or something along those lines?

**Comment by jgrosso** [comment]
@TheMatten AFAIK the following works as I would've originally expected:

``` hs

type Callback effs
   = forall openEffs. (Members effs openEffs) =>
                        Sem openEffs ()

foo ::
     forall callbackEffs ownEffs effs.
     (Members ownEffs effs, Members callbackEffs effs)
  => Callback callbackEffs
  -> Sem effs ()
foo = id
```

Thanks so much for the help, I appreciate your patience :)

**Comment by TheMatten** [comment]
I don't see why you want `ownEffs` here, but otherwise `foo` is basically proof that action that uses `Members` over type variable fits any list of effects that contains required ones.

NP :)
