### ISSUE TITLE
Typo in outputToTrace documentation

### ISSUE THREAD

**Issue by evanrelf** [polysemy-research/polysemy#189]
On version 1.0.0.0 of polysemy, [the documentation for `traceToOutput` reads](https://hackage.haskell.org/package/polysemy-1.0.0.0/docs/Polysemy-Trace.html#v:traceToOutput):

> `traceToOutput :: Member (Output String) r => Sem (Trace ': r) a -> Sem r a`
> Transform a Trace effect into a Output String effect.

However, the [documentation for `outputToTrace` _also_ reads](https://hackage.haskell.org/package/polysemy-1.0.0.0/docs/Polysemy-Trace.html#v:outputToTrace):

> `outputToTrace :: (Show w, Member Trace r) => Sem (Output w ': r) a -> Sem r a`
> Transform a Trace effect into a Output String effect.

I believe `outputToTrace` should say:

> Transform a ~Trace~ **Output String** effect into a ~Output String~ **Trace** effect.

**Comment by isovector** [comment]
It sure should. Good catch!
