### ISSUE TITLE
runState rewrite rules change strictness semantics

### ISSUE THREAD

**Issue by KingoftheHomeless** [polysemy-research/polysemy#192]
I ran into this while trying to make output effects (`Trace`, `Writer`, `Output`) more strict (which is a separate issue I'll open tomorrow). 

The easiest way to see this is to test with the following:
```haskell
runOutput :: Monoid o
          => Sem (Output o ': r) a
          -> Sem r (o, a)
runOutput =
  let lower = runState mempty
  in lower . reinterpret (\(Output a) -> do
        s <- get
        put $! s <> a
    )

test :: ()
test =
    snd
  . run
  . runOutput @String
  $ do
  output @String undefined
  return ()
```

When `lower` is marked `NOINLINE`, `test` throws an exception; if `lower` is marked `INLINE`, the `runState/reinterpret` rule of `Polysemy.State` will fire, and `test` will not throw an exception. You can also see it by removing the rule entirely, in which case `test` will throw an exception whether or not `lower` is marked `NO`/`INLINE`.

This is an issue because it's surprising behaviour, and it makes it difficult to write strict, stateful interpreters (like `runOutput` above is supposed to be).

I'm not entirely sure what makes the rewrite rule behave this way.

**Comment by isovector** [comment]
This is curious. I'm not entirely sure what's going on here. The rewrite rule just inlines your `\(Output a) -> ...` lambda inside the call to `stateful` (which `runState` is implemented as).

I've been looking for an opportunity to deploy [StrictCheck](http://hackage.haskell.org/package/StrictCheck) --- this might be a great opportunity!

**Comment by KingoftheHomeless** [comment]
Something's weird with the interaction of `stateful` and `runState`.

```haskell
runOutput :: Monoid o
          => Sem (Output o ': r) a
          -> Sem r (o, a)
runOutput =
  stateful (\_ s -> runState s undefined) mempty

test :: ()
test =
    snd
  . run
  . runOutput @String
  $ do
  output @String undefined
  return ()
```

Against all logic, this STILL doesn't throw an exception!

**Comment by KingoftheHomeless** [comment]
There are multiple layers of weirdness here.

First of all `stateful` itself is weird. Even using ```runOutput = stateful undefined mempty``` won't make the program crash.

This can be fixed by implementing `stateful` like this:
```
stateful f = interpretInStateT $ \e -> S.StateT $ \s -> do
  (s', a) <- f e s
  return (a, s')
```
instead of using the lazy `fmap swap`.

This leads to the following to successfully enforce strictness (i.e. it successfully crashes the program):
```haskell
runOutput =
      stateful (\(Output a) s -> do
                  let !s' = s <> a
                  return (s', ())) mempty
```

However, the following (which is what the rewrite rule produces) still doesn't work!
```haskell
runOutput =
      stateful (\(Output a) s -> runState s $ do
                  s' <- get
                  put $! s' <> a) mempty
```
So the problem must also lie in `runState`!

**Comment by KingoftheHomeless** [comment]
Yup! Also boiled down to the use of `fmap swap`.

This implementation causes the rewrite to work properly:
```
interpretInStateT f s (Sem m) = Sem $ \k -> do
  (a, s') <- flip S.runStateT s $ m $ \u ->
    case decomp u of
        Left x -> S.StateT $ \s' ->
          k . fmap swap
            . weave (s', ())
                    (uncurry $ interpretInStateT f)
                    (Just . snd)
            $ x
        Right (Weaving e z _ y _) ->
          fmap (y . (<$ z)) $ S.mapStateT (usingSem k) $ f e
  return (s', a)
{-# INLINE interpretInStateT #-}
```

I'll put up a pull request soon, which will close this and #193 .

**Comment by KingoftheHomeless** [comment]
Apparently this issue only manifests to begin with when you ran a Sem purely using `run`, and does not manifest if you used `runM` and `IO`. Weird.
