### ISSUE TITLE
polysemy-1.0.0.0 flaky test?

### ISSUE THREAD

**Issue by DanBurton** [polysemy-research/polysemy#195]
Just wanted to report that I saw the following test failure, but it did not fail again when I reran the test suite.

```
      test/AsyncSpec.hs:43:5: 
      1) Async.async should thread state and not lock
           ["1> hello","2> olleh","1> olleh"] does not contain ["1> hello","2> olleh","1> pong"]
```

This was on the stackage build server while building `nightly-2019-07-31`.

**Comment by KingoftheHomeless** [comment]
Happens to me too. I always figured it was due to my system.

This is not because of #186 , I had this issue since before then.

I could try to reimplement the test to use locks instead of sleeps, and that way make them more consistent.

**Comment by KingoftheHomeless** [comment]
This occurs rather rarely for me. I've only been able to reproduce it twice (with the old version) over the ~50 tests I've run over the last half hour, and only when running all tests, and not specifically `AsyncSpec`. Is it possible that the uses of `parallel` in the other tests messes with the use of concurrency in `AsyncSpec`?

**Comment by isovector** [comment]
> Is it possible that the uses of parallel in the other tests messes with the use of concurrency in AsyncSpec?

That seems feasible to me. The time scales involved are probably small enough that a busy scheduler might miss interleaving them.

**Comment by KingoftheHomeless** [comment]
If anyone still runs into this even after #197, please reopen this issue.
