### ISSUE TITLE
TH should give error about missing `DataKinds` extension

### ISSUE THREAD

**Issue by TheMatten** [polysemy-research/polysemy#201]
Currently, use of `makeSem`(`_`) without `DataKinds` results in error:
```
Parsemy.hs:18:1-16: error:
    Illegal type: ‘"Parsemy"’ Perhaps you intended to use DataKinds
   |
18 | makeSem ''Parser
   | ^^^^^^^^^^^^^^^^
```
which is not bad, but does not explicitly say that we depend on that extension.
The only change needed should be adding extension to list of required ones [here](https://github.com/polysemy-research/polysemy/blob/829e3202fc7d09faaf757cddd11a8a741b687a70/src/Polysemy/Internal/TH/Effect.hs#L125).
https://github.com/polysemy-research/polysemy/blob/829e3202fc7d09faaf757cddd11a8a741b687a70/src/Polysemy/Internal/TH/Effect.hs#L125

**Comment by pepegar** [comment]
I could tackle this one :)
