### ISSUE TITLE
`MemberWithError`, required for `output` is only exported from `Internal.Union`

### ISSUE THREAD

**Issue by Heimdell** [polysemy-research/polysemy#231]
Subj.

Please export it from `Polysemy` or (`Polysemy.Output` and other modules that use it).

**Comment by KingoftheHomeless** [comment]
`MemberWithError` only adds a constraint that will evaluate to `()` if no type errors have occurred. `Member` is enough to satisfy `MemberWithError`. The reason why `Member` isn't `MemberWithError` is detailed in the discussion of #227.

That said, perhaps we should export `MemberWithError` anyway for the user to opt into the problematic error messages in a context where they won't cause any issue.

**Comment by KingoftheHomeless** [comment]
Actually, turns out `Member` doesn't actually satisfy `MemberWithError` straight-up, when the given effect is polymorphic!
```haskell
no :: forall e r a. Member e r => (MemberWithError e r => Sem r a) -> Sem r a
no a = a
```
Doesn't compile, but
```haskell
newtype Wrapped e m a where
  Wrapped :: e m a -> Wrapped e m a

yes :: forall e r a. Member (Wrapped e) r => (MemberWithError (Wrapped e) r => Sem r a) -> Sem r a
yes a = a
```
Does! Not sure if that matters, though.
