### ISSUE TITLE
Extraction of IO errors

### ISSUE THREAD

**Issue by incertia** [polysemy-research/polysemy#243]
There are a lot of libraries that run their logic entirely in IO. For example, all the fundamental `wreq` logic, e.g. `get`, `post`, are done in IO. I've written a helper function to interpret these types of DSLs with `polysemy`'s `Error` feature.

```haskell
withIOError :: (Exception e, Member (Embed IO) r, Member (Error e) r) => (e -> Sem r a) -> IO a -> Sem r a
withIOError handler action = do
  res <- embed $ try action
  case res of
       Left e  -> handler e
       Right x -> pure x
```

However, this helper has the issue of being purely restricted to `IO`. Namely, when combined with an interpreter, it looks like

```haskell
runWreqIO = interpret $ withIOError @HttpException throw . \case
  -- ...
```

and the `case` expression must result in an `IO a`. Is there any way to replace `IO a` with `Sem r' a` for a good choice of `r'`?

Another issue is that in probably 99.9% of cases one would want `handler = throw` and then combine the different error types with `mapError`. I have tried removing the `(e -> Sem r a)` in which case the `e` type becomes existential in the type signature but I am unsure how to proceed from there. GHC suggests `AllowAmbiguousTypes` and `case`'ing on `Left (e :: e)` does not seem to work.

```haskell
withIOError :: (Exception e, Member (Embed IO) r, Member (Error e) r) => IO a -> Sem r a
withIOError action = do
  res <- embed $ try action
  case res of
       Left (e :: e)  -> throw @e e
       Right x -> pure x
```

I get the error

```
    • Ambiguous use of effect 'Error'
      Possible fix:
        add (Member (Error e) r) to the context of 
          the type signature
      If you already have the constraint you want, instead
        add a type application to specify
          'e' directly, or activate polysemy-plugin which
            can usually infer the type correctly.
    • In the expression: throw @e e
      In a case alternative: Left (e :: e) -> throw @e e
      In a stmt of a 'do' block:
        case res of
          Left (e :: e) -> throw @e e
          Right x -> pure x
   |
48 |        Left (e :: e)  -> throw @e e
   |
```

Any guidance on how to proceed?

EDIT: defaulting to `throw` can be fixed by using an explicit `forall`. We still need `AllowAmbiguousTypes`.

```haskell
withIOError :: forall e r a . (Exception e, Member (Embed IO) r, Member (Error e) r) => IO a -> Sem r a
withIOError action = do
  res <- embed $ try action
  case res of
       Left (e :: e)  -> throw @e e
       Right x -> pure x
```

**Comment by KingoftheHomeless** [comment]
Yes, there indeed is a way to replace `IO` with `Sem r`: use `Final IO`!

```haskell
import qualified Control.Exception as X

catchIOError  (Exception e, Member (Final IO) r) => Sem r a -> (e -> Sem r a) -> Sem r a
catchIOError m h = withStrategicToFinal $ do
  m' <- runS m
  h' <- bindS h
  s  <- getInitialStateS
  pure (m' `X.catch` \e -> h' (e <$ s))
```
This will intercept any IO exceptions thrown by the left-hand argument.

As for rethrowing exceptions; the ambiguity issues feel like something that should get resolved by `polysemy-plugin`. Are you using the plugin?

**Comment by incertia** [comment]
See [gist](https://gist.github.com/incertia/ef626297ae541f71c1caf9350fb7e09f) for how @KingoftheHomeless's `lower` interpreter works in action.

**Comment by KingoftheHomeless** [comment]
For anyone confused, I contacted `incertia` on Discord and offered help there. They used Polysemy v1.0, so a `Final` solution wasn't an option, so I offered a `lower-` interpreter based solution instead.
