### ISSUE TITLE
Lack of examples how to use `reinterpretH{,2,3...}`

### ISSUE THREAD

**Issue by Heimdell** [polysemy-research/polysemy#260]
I have following effects:

```haskell
data Builtins (m :: * -> *) a where
  Builtin :: Name.T -> Builtins m ()

data HasContext m a where
  Find :: Name.T -> HasContext m Program
  With :: ContextFrame -> m a -> HasContext m a
```

Let's say, I want to convert `HasContext : r` effect stack to `Reader Context : Builtins : r` one.

I write

```haskell
runContext
  :: Sem (HasContext : r) a
  -> Sem (Reader Context : Builtins : r) a
runContext = reinterpret2H \case
  Find name -> do
    ctx <- ask
    case Context.find name ctx of
      Just it -> do
        pureT it

      Nothing -> do
        builtin name
        pureT Nop

  With frame action -> do
    local (Context.add frame) do
      m <- runT action
      _wat
```

I can nor figure out neither find an example on what to do next. 

The `m` has type

```haskell
m :: Sem (HasContext : Reader Context : Builtins : r) (f x)
```

The question:
1) Why `HasContext` is still there? I see tha you call `runReader` in `runReader` and got very very confused.
2) How do I get it out? If I apply `runContext`, I get duplicated `Reader Context` and `Builtins`.

P.S.: I can just use `interpretH` and refer to the `Reader Context` and `Builtins` as `Member _ r`, but that raises a questions about reasons for `reinterpretHN` to exist. Can you provide an example, that shows it in simple case, in less simple case and in a full glory?

**Comment by KingoftheHomeless** [comment]
1. `HasContext` is still there to give you extra flexibility of how you interpret higher-order occurrences of `Sem (HasContext ': r) a` within each action. This is a feature of `Tactics` in general, and is important for `local` of `runReader` and `listen`/`censor` of `runWriter` to work properly (although @isovector admits that the need for it in `listen` is kinda stupid).
2. Use `subsume`! It was added to the library for exactly this use-case.

About the P.S.; `reinterpret/H` and friends are meant primarily as a combinator for building other interpreters. It's for when you want to add a new effect to the effect stack, and then interpret the newly introduced effect. This means that you can leverage existing effects and interpreters to build new interpreters without having to demand that the effects you want to use already exists within the effect stack. `runWriter` is the perfect example of this using `interpretH`, and `runOutputMonoid` is a simpler example using `reinterpret`.

**Comment by isovector** [comment]
After spending a few hours today fighting with some of the lesser-used combinators in polysemy, I can greatly sympathize with this request.

**Comment by isovector** [comment]
Did you ever resolve this? What is the type of `_wat`?

**Comment by Heimdell** [comment]
Nope, I didn't. I ended with

```haskell
runContext
  ::  Members '[Reader Context, Builtins] r
  => Sem (HasContext : r) a
  -> Sem r a
```

via some other combinator.

**Comment by isovector** [comment]
I think that is probably for the best. I'm beginning to question the value of any of the reinterpretations.
