### ISSUE TITLE
Coroutine effect

### ISSUE THREAD

**Issue by KingoftheHomeless** [polysemy-research/polysemy#264]
A coroutine effect a-la `freer-simple` is possible (I've split its `Yield` into `Yield` and `Receive` here):

```haskell
import Control.Monad.Free.Church -- from the "free" package

cataSem :: (a -> b) -> (Union r (Sem r) b -> b) -> Sem r a -> b
cataSem b c sem = runF (runSem sem liftF) b c


data Coroutine i o m a where
  Yield   :: o -> Coroutine i o m ()
  Receive :: Coroutine i o m i

makeSem ''Coroutine
data Status r i o a
  = Finished a
  | IsYielding o (Sem r (Status r i o a))
  | IsReceiving (i -> Sem r (Status r i o a))
  deriving (Functor)

bindStatus :: (a -> Sem r (Status r i o b))
           -> Sem r (Status r i o a)
           -> Sem r (Status r i o b)
bindStatus f sm = sm >>= \case
  Finished a -> f a
  IsYielding o rs -> pure $ IsYielding o (bindStatus f rs)
  IsReceiving rs  -> pure $ IsReceiving (bindStatus f . rs)

distribStatus :: Status r i o (Sem (Coroutine i o ': r) a)
              -> Sem r (Status r i o a)
distribStatus = \case
  Finished a      -> launch a
  IsYielding o rs -> pure $ IsYielding o (bindStatus launch rs)
  IsReceiving rs  -> pure $ IsReceiving (bindStatus launch . rs)

launch :: Sem (Coroutine i o ': r) a -> Sem r (Status r i o a)
launch = cataSem (pure . Finished) $ \u -> case decomp u of
  Right (Weaving e s _ ex _) -> case e of
    Yield o ->
      pure $ IsYielding o (ex s)
    Receive ->
      pure $ IsReceiving (\i -> ex (i <$ s))
  Left g -> do
    bindStatus id $
      liftSem $ weave
        (Finished ())
        distribStatus
        (\case { Finished a -> Just a; _ -> Nothing})
        g
```

However, there's probably some issue with this, seeing how `fused-effects` decided not to implement a `Coroutine` effect.

One noticeable downside is that the inspector can only inspect `Status` if no `yield`s/`receive`s has been made, even though a value of `a` is still present within the continuation (but unretrievable). This violates the assumption made by `fixpointToFinal`.

I also wonder if we should add more features. Perhaps more actions than simply `yield`/`receive`, and/or perhaps some nice interface for interacting with launched coroutines that mutably updates the status of a launched coroutine.

There's also the question if this belongs in `polysemy` or `polysemy-zoo`.

**Comment by KingoftheHomeless** [comment]
Here's a problem:
```haskell
generator :: Members '[Coroutine () Int, Reader Int] r
          => Sem r ()
generator = local (+1) $ do
  ask >>= yield
  ask >>= yield

test :: Member (Output Int) r
     => Sem r ()
test = runReader 0 $ do
  launch generator >>= \case
    IsYielding i rs -> output i >> rs >>= \case
      IsYielding j _ -> output j
      _ -> pure ()
    _ -> pure ()
```
```haskell
run (runOutputList test) == ([1,0], ())
```

Higher-order actions of a coroutine only apply up until the first `yield`/`receive`, since the continuations are hidden in the functorial state, and can't be touched, similar to the problems with `NonDetState`. That's bad!

**Comment by robrix** [comment]
> However, there's probably some issue with this, seeing how `fused-effects` decided not to implement a `Coroutine` effect.

Our choice not to implement this boils down to:

1. It doesn’t have to be implemented in `fused-effects` to be useful, unlike e.g. `Reader r` where we couldn’t provide (non-orphan) `Algebra` instances for `((->) r)` or `ReaderT` without defining it in the library.

2. Relative to e.g. `Reader` or `State`, it’s much less obvious what the right phrasing of the effect is. Oleg’s formulation didn’t report final results via `Status`, for example, tho `freer-simple` does.

So it’s not something inherent to the coroutine effect, but rather that if we do this, we want to be sure we’ve done it right, and we don’t really have a good way to drive that right now without a concrete use case—or better, a family of such.

**Comment by isovector** [comment]
I'm on the same page as @robrix here; I didn't add the coroutine effect in the original libary because I had no idea what it should look like.

**Comment by KingoftheHomeless** [comment]
Alright. With that in mind, and how it doesn't seem to be validly implementable through `weave`, I'm going to close this issue.
