### ISSUE TITLE
Interpreters don't compose nicely

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#277]
I am trying to race two `Input` interpreters; the result is a nightmare and took me an hour to work out.

```haskell

raceInput
    :: Member (Final IO) r
    => InterpreterFor (Input i) r
    -> InterpreterFor (Input i) r
    -> InterpreterFor (Input i) r
raceInput i1 i2 m = withWeavingToFinal $ \st lower ins -> do
  let i1' = lower $ (<$ st) $ i1 input
  let i2' = lower $ (<$ st) $ i2 input
  runSem (fmap (<$ st) m) $ \u ->
    case decomp u of
      Left x -> do
        z <- lower $ (<$ st) $ liftSem $ hoist (raceInput i1 i2) x
        pure $ fromJust $ ins z
      Right (Weaving Input st' _ y _) -> do
        z <- race i1' i2'
        pure $ y $ (<$ st') $ fromJust $ ins $ either id id $  z
```

Disgusting, and probably doesn't work very well.

**Comment by isovector** [comment]
@KingoftheHomeless do you have any ideas on how to make this particular interpreter nicer? The final stuff still does my head in.

**Comment by isovector** [comment]
Came up with this, which is much nicer semantically. Not sure how I feel about passing the buck to `streaming`, though.

```haskell

merge
    :: MonadIO m
    => S.Stream (S.Of a) IO ()
    -> S.Stream (S.Of b) IO ()
    -> S.Stream (S.Of (Either a b)) m ()
merge sa sb = do
  mvar <- liftIO $ do
    mvar <- newEmptyMVar
    void . forkIO $ S.mapM_ (putMVar mvar . Left) sa
    void . forkIO $ S.mapM_ (putMVar mvar . Right) sb
    pure mvar
  S.repeatM . liftIO $ takeMVar mvar

runInputViaStream
    :: Member (Embed IO) r
    => S.Stream (S.Of i) IO ()
    -> InterpreterFor (Input i) r
runInputViaStream stream m = do
  (inchan, outchan) <- embed newChan
  void $ embed $ forkIO $ S.mapM_ (writeChan inchan) stream
  interpret (\Input -> embed $ readChan outchan) m
```

**Comment by KingoftheHomeless** [comment]
How about this:
```haskell
import qualified Control.Concurrent.Async as A

raceInput
  :: forall i r
   . Member (Final IO) r
  => InterpreterFor (Input i) r
  -> InterpreterFor (Input i) r
  -> InterpreterFor (Input i) r
raceInput intr1 intr2 = interpret $ \Input -> withStrategicToFinal $ do
  input1 <- runS (intr1 input)
  input2 <- runS (intr2 input)
  pure $ either id id <$> A.race input1 input2
```

**Comment by KingoftheHomeless** [comment]
You could want to apply both interpreters over the entire block of actions (e.g. if they do something `View`-like). That would require more tinkering, but it should be possible by leveraging `Tagged`.

**Comment by isovector** [comment]
@KingoftheHomeless cool, thanks! Do either of these solutions work if the interpreter does some `IO` work before calling `interpret`? This is the particular interpreter I'd like to race:

```haskell
inputToFileWatch
    :: Member (Embed IO) r
    => FilePath
    -> Sem (Input Event ': r) a
    -> Sem r a
inputToFileWatch fp m = do
  (inchan, outchan) <- embed newChan
  ino <- embed startManager
  void . embed
       . watchDir ino fp (const True)
       $ writeChan inchan
  z <- interpret (\Input -> embed $ readChan outchan) m
  embed $ stopManager ino
  pure z
```

**Comment by KingoftheHomeless** [comment]
If you don't want that work duplicated, then you must use the latter solution. That solution only uses each provided interpreter once.

**Comment by isovector** [comment]
Oh, I see how this works. Elegant. Thanks!

**Comment by isovector** [comment]
Is there some way to hide the `(Tagged "intr1" (Input i) ': r)` bit from the tysig?

**Comment by KingoftheHomeless** [comment]
I don't think so, but you could define a newtype effect of `Input` that isn't exposed instead of `Tagged "intr1"`, so the user can't muck with it.

**Comment by isovector** [comment]
Thanks again! Is this the recommended way of using `Final`, via `withStrategicToFinal` inside of an `interpret`?

**Comment by KingoftheHomeless** [comment]
Yes; typically, you need to have a `withStrategicToFinal`/`withWeavingToFinal` for each action you interpret.

You can't use a single `withWeavingToFinal`/`withStrategicToFinal`, and then inside of it collapse a `Sem (e ': r)` on an action-per-action basis to `IO (f x)`, since the distribution `f (Sem r x) -> IO (f x)` doesn't provide enough power to do that. This hurts a lot, because if it were possible it'd enable a lot of cool stuff.

**Comment by KingoftheHomeless** [comment]
@isovector Should this issue be closed?

**Comment by isovector** [comment]
Yeah, let's close this specific issue. I am still very concerned that "interpreters don't compose nicely," but I suppose that's the thing we're trying to solve with all of this.
