### ISSUE TITLE
Conditional effects

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#281]
I just realized we can use the typeclass machinery to determine whether or not an effect exists in our stack. The machinery (with crap names is this):

```haskell
data Has e r where
  Has   :: MemberNoError e r => Has e r
  Hasnt :: Has e r

class HasHas (e :: Effect) (r :: EffectRow) where
  hasHas :: Has e r

instance HasHas e '[] where
  hasHas = Hasnt

instance {-# OVERLAPPING #-} HasHas e r => HasHas e (e ': r) where
  hasHas = Has

instance ( HasHas e r
         , IndexOf (e2 ': r) (Found (e2 ': r) e) ~ e
         , Found (e2 ': r) e ~ 'S (Found r e)
         ) => HasHas e (e2 ': r) where
  hasHas =
    case hasHas @e @r of
      Has   -> Has
      Hasnt -> Hasnt
```

and can be used thusly:

```haskell
tryGet :: forall s r. HasHas (State s) r => Sem r (Maybe s)
tryGet =
  case hasHas @(State s) @r of
    Has   -> pure <$> get
    Hasnt -> pure Nothing
```

```haskell
> run $ runState "hello" $ tryGet @String
("hello",Just "hello")

> run $ tryGet @String
Nothing
```

I'm not sure what to do with this, but it's pretty neat.

**Comment by isovector** [comment]
In fact, this generalizes:

```haskell
try :: forall e r a. HasHas e r => (Member e r => Sem r a) -> Sem r (Maybe a)
try e =
  case hasHas @e @r of
    Has   -> pure <$> e
    Hasnt -> pure Nothing
```

**Comment by KingoftheHomeless** [comment]
This kind of power can also be derived from `Typeable r`. Of course, we don't want _that_ much power, but perhaps it's possible to generalize `HasHas` in a similar way, like this:

```haskell
class Concrete r where
  checkMembership :: forall e. Typeable e => Has e r
```

I'll look into it.

**Comment by KingoftheHomeless** [comment]
Actually, #110 wouldn't help with this: you can't deduce `Member e r` from `Elem r e`, since `Member e r` always targets the first occurrence of `e` in `r`, while `Elem r e` could serve as a proof for a later occurrence. The best you can do is:
```haskell
sendUsing :: Elem r e -> e (Sem r) a -> Sem r a
```
What a pain.

**Comment by expipiplus1** [comment]
Looks a little similar to what was being discussed here: https://github.com/polysemy-research/polysemy/issues/315
