### ISSUE TITLE
Reader for compact regions

### ISSUE THREAD

**Issue by spacekitteh** [polysemy-research/polysemy#283]
Obviously, it requires 'compact'  being linked. Would this be more appropriate for polysemy-zoo?

```haskell
import Control.Monad.IO.Class

import Data.Compact

-- | Run a 'Reader' effect by compacting a value; otherwise behaves as normal. Useful for 'Reader' effects which provide a large structure.
runReaderWithCompacted :: forall r i a . Member (Embed IO) r => i -> Sem (Reader i ': r) a -> Sem r a
runReaderWithCompacted i sem = do
    compacted <- liftIO (compactWithSharing i)
    runReaderWithExistingCompacted compacted sem
{-# INLINE runReaderWithCompacted #-}

-- | Run a 'Reader' effect with a value in a compact region. Will not add 'Local' values to the existing region, but will create a new region for it.
runReaderWithExistingCompacted :: forall r i a . Member (Embed IO) r => Compact i -> Sem (Reader i ': r) a -> Sem r a
runReaderWithExistingCompacted i =
    interpretH $ \case
        Ask -> pureT (getCompact i)
        Local f m -> do
            mm <- runT m
            let transformed = f (getCompact i)
            raise $ runReaderWithCompacted transformed mm
{-# INLINE runReaderWithExistingCompacted #-}
```

**Comment by isovector** [comment]
I'm not entirely sure what a compact region is --- mind giving me a high-level walk through what's going on here?

**Comment by spacekitteh** [comment]
Sure! A compact region is basically a read-only piece of memory that the GC skips over - so if you have, say, a 1GB data structure you need to keep in memory as you're often referring to, but not changing, you can *compact* it, so that the GC doesn't waste time inspecting the internals of it all the time. 

The 'sharing' part of 'compactWithSharing' means that it only stores one copy of each individual object (as in, by reference), rather than duplicating them (by value).

The compact region is freed all at once, once there are no more references to it from outside of the region.

Two examples for this specific interpreter:
1. A (language) dictionary - typically, a language dictionary or a corpus etc doesn't change during runtime.
2. For my SMT solver, assertions are stored as a stack of sets of terms. We don't want to modify the input, so we want to keep it around for reference due to constant search restarts, but we also don't want to waste time in the GC going over GBs of parse trees at each GC epoch.

**Comment by isovector** [comment]
Cool, thanks! This seems like a good fit for the zoo --- mind moving the PR over to there?

**Comment by spacekitteh** [comment]
I don't think I actually made a PR lol - I'll make one in the next few days

**Comment by spacekitteh** [comment]
A'ight, I made a PR on -zoo :)

**Comment by spacekitteh** [comment]
Merged in https://github.com/polysemy-research/polysemy-zoo/pull/59
