### ISSUE TITLE
Effect subsets

### ISSUE THREAD

**Issue by adamConnerSax** [polysemy-research/polysemy#290]
Apologies in advance if this has already been covered.

Is there any way to express something like

```
runInLarger :: EffectsSubset r r' => EffectOrderAgnostic (Sem r a) -> Sem r' a
```
?

Is that something that all that new ```subsume``` machinery can help with?  Can I somehow make the effects in ```r``` into a ```Bundle``` and then ```subsume``` them?

**Comment by isovector** [comment]
This thing will "just work" for any concrete stack.

```haskell
smaller :: Members stuff r => Sem r a

larger :: (Members stuff' r. Members stuff r) => Sem r' a
larger = do
  smaller
  blah
```

The answer really depends on what you're trying to do here!

**Comment by adamConnerSax** [comment]
Yeah.  What I actually have is this:
```
data CachedAction es a where
  Made :: a -> CachedAction es a
  RetrieveOrMake :: S.Serialize b => T.Text -> (forall r. P.Members es r => P.Sem r b) -> (b -> a) -> CachedAction es a
```
which is intended as a way to carry around a thing that we might get from a cache (which holds ```b```s) or make, using the action, or might have already gotten and stored in the ```Made``` constructor.

The issue, and I might just have gone round in some silly way and now be lost, is how to carry that action around and most easily be able to run it in any stack which has the effects it needs.  That is, I want to make the ```CachedAction``` and give it as an argument to a thing that needs the ```a```.  Then if that thing never gets called, I won't ever execute the action, which might be costly, but if I do need it, I can run the action, as long as I have the effects I need in the stack at that point.

This is all a poor substitute for a thing like a build system or something like FunFlow, an arrow based dependency manager.  I just want a simple way to save results of computations and only compute/retrieve the ones I need the next time around.  And even retrieving from cache might be expensive since it might involve deserializing a big structure.  So I want to take advantage of laziness to not run the action/retrieve the data from cache unless I use it.

Does that make any sense?

**Comment by isovector** [comment]
I usually model this sort of thing with an `intercept`ion of some other effect. Caching is an implementation detail, and almost never needs to appear directly in your application code. Check out [`View`](https://github.com/polysemy-research/polysemy/blob/master/src/Polysemy/View.hs) for how I usually tackle things like this!

**Comment by adamConnerSax** [comment]
Cool!  I'll check that out.  And close this for now...

Thanks!
