### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#292]
Hi all,

I've decided to take a software hiatus, and don't want to leave polysemy users dead in the water. As such, I'm looking for someone willing to step up as the official maintainer. The project is mostly self-sufficient at this point, the majority of the work is responding to github issues, and occasionally pushing new releases to hackage. I'd estimate the amount of work  to be around one hour per week.

Let me know if you're interested. Thanks!

**Comment by KingoftheHomeless** [comment]
I'm definitely open to maintain polysemy when it comes to fixing semantic bugs and providing support. I have a very good grasp of the internals of polysemy, so I'll be able to cover anything related to the implementation of the library, with the exception of TH. When I'm not occupied with my studies, I can also do heavy work on providing documentation and adding features. My weak spots are optimization, and fiddling with GHC and Stack. I'll have a hard time with issues in the vein of #91 and #235. I also have no experience with Hackage.

I don't think I'll do as a solo maintainer, but perhaps a team could be formed? @TheMatten has experience with TH and the plugin, and @googleson78 has experience mucking with Stack.

**Comment by TheMatten** [comment]
@KingoftheHomeless You can count with me, I just won't be productive during approx. next month or two (school stuff).

**Comment by googleson78** [comment]
I'm also on board - I generally try to help with issues that I have some idea about what to do. (and am also interested in learning more about internals along the way)

(btw, are we all students? :sweat_smile:)

**Comment by TheMatten** [comment]
@googleson78 Haha, @isovector moving project to his student workforce 😜

**Comment by Heimdell** [comment]
I'm interested.

**Comment by isovector** [comment]
Thanks for stepping up, everyone! I've added @KingoftheHomeless , @TheMatten and @googleson78 to the maintainers group both of this project and of `polysemy-research` at large. I've added @TheMatten as a hackage maintainer. I'll let you three sort it out from here, and have absolutely trust in all of you.

@Heimdell thanks for the interest! Please get in touch with any of the above three to see if they could use the help.

Cheers!

**Comment by TheMatten** [comment]
@KingoftheHomeless @googleson78 Are you interested in having some place where we can discuss things in real time? We could e.g. have room on https://funprog.zulipchat.com. It's public so people can still freely "sneak in" and it may be good place for discussing things sooner than we create issue/PR for them.

**Comment by TheMatten** [comment]
@KingoftheHomeless @googleson78 Are you interested in having some place where we can discuss things in real time? We could e.g. have room on https://funprog.zulipchat.com. It's public so people can still freely "sneak in" and it may be good place for discussing things sooner than we create issue/PR for them.

**Comment by TheMatten** [comment]
Okay, so I've created one: https://funprog.zulipchat.com/#streams/216942/Polysemy
