### ISSUE TITLE
Combinator for embedding errors in a 'MonadError'

### ISSUE THREAD

**Issue by googleson78** [polysemy-research/polysemy#306]
Would this combinator be useful?:
```haskell
embedError 
  :: forall e1 e2 m r a
   . (MonadError e2 m, Member (Embed m) r) 
  => (e1 -> e2) -> Sem (Error e1 ': r) a -> Sem r a
embedError conv = embed <=< fmap (liftEither . first conv) . runError
```

I just wrote it for use in aggregating my multiple error types into `servant`s `Handler`, which is a `MonadError ServerError` (which I notably only **throw** from my program for now - no catching)

I'm aware of the existence of [errorToFinal](https://hackage.haskell.org/package/polysemy-zoo-0.6.0.1/docs/Polysemy-Final-MTL.html#v:errorToFinal), which confuses me, because of its more involved implementation - i.e. am I even doing the right thing here.

**Comment by adamConnerSax** [comment]
There is also https://github.com/polysemy-research/polysemy-zoo/blob/master/src/Polysemy/ConstraintAbsorber/MonadError.hs
in the zoo, if that's any help dealing with a ```MonadError``` constraint.  Not sure if it's been released, though.

**Comment by Heimdell** [comment]
I use this thing to collect errors in one megatype:

```haskell
data Union xs where
  Here  ::       x  -> Union (x : xs)
  There :: Union xs -> Union (x : xs)

class OneOf x xs where
  inject  :: x -> Union xs
  project :: Union xs -> Maybe x

instance {-# OVERLAPS #-} OneOf x (x : xs) where ...
instance {-# OVERLAPPABLE #-} OneOf y xs => OneOf y (x : xs) where ...

addError
  :: forall err errs r a
  .  ( Member (Error (Union errs)) r
     , OneOf err errs
     )
  => Sem (Error err : r) a
  -> Sem r a
addError ma = do
  mea <- runError ma
  either (throw . inject) return mea
```

and then I do

```haskell
  ...
  $ runError
  $ addError @Expected
  $ addError @NotFound
  $ addError @MemoryCorruption
  $ ...
```

I have to notice, that I got

```haskell
type AllErrors = Union
  [ Expected
  , NotFound
  , MemoryCorruption
  ]
```

and I use it in the signature of the function where the `addError`-chain is copied from.
