### ISSUE TITLE
[feature request] Interpret two effects at once

### ISSUE THREAD

**Issue by Heimdell** [polysemy-research/polysemy#309]
I have the following effect:

```haskell
data Parallel m a where
  Parallel :: m a -> Parallel m ()

makeSem ''Parallel
```

I also have the following runner:

```haskell
runParallelButNotReally
  :: forall e a r. Sem (Parallel : r) a -> Sem r a
runParallelButNotReally = interpretH \case
  Parallel ma -> do
    it <- runT ma
    raise do
      fa <- runParallelButNotReally it
      return (fa $> ())
```

The desired semantics is to run some action for [some of] its side effects.

The problem is, I have `Error` in my effect stack. Therefore this runner of `Parallel` can fail in that `action` and then `parallel action` will fail as well.

[How] can I `interpretH` _with_ the `Error` effect, so I can make `Error` to do what I need?

I imagine some
```haskell
runParallelAndIgnoreErrors
  :: (..., Members [..., Error e] r) => Sem (Parallel : Error e : r) a -> Sem r a
```
but I cannot figure how to do it using `interpretH`.

**Comment by KingoftheHomeless** [comment]
You have access to the entire effect stack during interpretation using `interpretH`, so you can do actions like `catch`. You can also use `getInitialStateT` if you need the effectful state `f ()` but don't have it available through the result of some action (for example, if the action failed). So you can do this:

```haskell
runParallelButNotReallyAndIgnoreErrors
  :: forall e a r. Member (Error e) r => Sem (Parallel : r) a -> Sem r a
runParallelButNotReallyAndIgnoreErrors = interpretH \case
  Parallel ma -> do
    it <- runT ma
    s <- getInitialStateT
    raise do
      fmap ($> ()) (runParallelButNotReally it) `catch` \(_ :: e) -> return s
```

And thus running the action, but throwing away all errors of type `e`.
