### ISSUE TITLE
Restrictive upper bound on first-class-families

### ISSUE THREAD

**Issue by jkachmar** [polysemy-research/polysemy#312]
`polysemy` has restrictive upper bounds on `first-class-families` (>=0.5.0.0 && < 0.7), which causes it to fail to build with `first-class-families-0.7.0.0`.

I'm posting an issue here (rather than just at commercialhaskell/stackage#5117) because Sandy's the point-of-contact for this library and I know he's taking a break at the moment.

**Comment by KingoftheHomeless** [comment]
Bounds of v1.2.3.0 now also updated on Hackage.
