### ISSUE TITLE
Catching/masking of "error" and the like

### ISSUE THREAD

**Issue by adamConnerSax** [polysemy-research/polysemy#323]
I'm pretty sure this question is answered in another issue but my understanding of async and exception handling is very iffy so I'm not sure how to figure it out.

I discovered that things like "error" are being swallowed in my polysemy app.

The specific case was a line of code where I messed up a variable name so I had something like ``` k = someText <> k``` which, at run time does something like "error" when evaluated.  

Instead of seeing that error, I got a deadlock error (an STM or MVar thing) which I eventually traced to the fact that what I thought was my main thread--the one I had launched a logging thread from and the only one able to send the logging thread a message to exit--had died.  
And then I figured out that it had died because of the above error.  But something had swallowed that exception and thus instead of seeing the error I just got the deadlock. 

I'm not sure how to simplify it to an example since the infrastructure is sort of large.  But does anyone have a hint for where I might look to figure out why it's happening and maybe fix it?

My polysemy stack has many effects in it but the "base" of it is run by
```
 P.runM
    . embedToMonadIO @m -- interpret (Embed IO) using m
    . runError
    . asyncToIO
```
(where, in the case I am observing, ```m``` is ```IO```)

and I imagine the confusing thing is happening in there someplace.

**Comment by KingoftheHomeless** [comment]
It's `asyncToIO`. The machinery behind it is very fragile, and prone to breaking. Use `asyncToIOFinal` and `errorToIOFinal` instead to to avoid any potential weirdness (but with the usual caveats of using a `-Final` interpreter).

That said, it should be possible to prevent `asyncToIO` from breaking on exceptions thrown through `error`. In fact, I thought the machinery already in place would take care of that... if you give me a small test-case, I'll see what I can do.

**Comment by adamConnerSax** [comment]
Thanks!

I’ll look to see if I can make a test case but I’m not sure it’s going to be easy to make it small.

I’ll look at the Final versions. I’ve avoided them because I want to keep the ability to run the polysemy stack and end up with something other than IO, but which has an instance of MonadIO. Maybe that flexibility isn’t worth it.

Adam

**Comment by adamConnerSax** [comment]
So I don't think the tradeoff making ```IO``` final is worth it to me.  Would there be a way to have an ```asyncToMonadIOFinal``` that would work just like ```asyncToIOFinal```?  This seems like a useful bit of power because then people get all the polysemy Final stuff on top of anything with ```IO``` in it, rather than only ```IO``` itself.  
But I'm assuming there's a reason various things are implemented in terms of ```Final IO``` itself rather than ```(MonadIO m, Final m)```.  
The difference came up for me because I was implementing a polysemy stack on top of the ```PandocMonad```. I replaced that with a ```Pandoc``` effect, but it made me realize that there may be other cases where you want to add effects to an existing monad that is less simple to replace.  Or you might just want to skip the work.

**Comment by KingoftheHomeless** [comment]
Nope. You _could_ create the following
````haskell
finalToFinalBaseControl :: (MonadBaseControl b m, Final m) => (forall x. StM m x -> Maybe x) -> Sem (Final b ': r) a -> Sem r a
```
And thus you can interpret `Async` in terms of `Final m` given `MonadBaseControl IO m`. But `MonadIO m` is not enough to (safely) interpret `Async`.

If you want, I could write up the implementation for `finalToFinalBaseControl` (it's messy, and I lost it somewhere, but I know how to write it), which you can temporarily use, and then we on the polysemy team can discuss if it merits adding to `polysemy`, `polysemy-zoo`, or possibly some new library.

**Comment by KingoftheHomeless** [comment]
I remade it. It's a lot prettier now `transform` exists.

```haskell
data StMF m a where
  StMF :: !(a -> b) -> StM m a -> StMF m b
deriving instance Functor (StMF m)

runStMF :: MonadBaseControl b m
        => StMF m a
        -> m a
runStMF (StMF ex st) = ex <$> restoreM st
{-# INLINE runStMF #-}

inspectStMF :: (forall x. StM m x -> Maybe x)
            -> StMF m a
            -> Maybe a
inspectStMF ins (StMF ex st) = ex <$> ins st
{-# INLINE runStMF #-}

-- | If @b@ is the base of the monad @m@, run a @'Final' b@ effect by
-- transforming it into a @'Final' m@ effect.
--
-- 'finalToFinalBaseControl' needs to be provided an inspector for the
-- reified state of @m@. This is very important for multiple effects such as
-- 'Polysemy.Async.Async', 'Polysemy.Writer.Writer',
-- and 'Polysemy.Fixpoint.Fixpoint'. Please don't simply
-- provide @const Nothing@, but rather a function that extracts a value
-- from the state whenever possible.
finalToFinalBaseControl :: forall m b r a
                         . (MonadBaseControl b m, Member (Final m) r)
                        => (forall x. StM m x -> Maybe x)
                           -- ^ Inspector.
                           -- Unfortunately, this needs to be provided
                           -- by hand as 'MonadBaseControl' doesn't provide one.
                        -> Sem (Final b ': r) a
                        -> Sem r a
finalToFinalBaseControl ins' = transform $ \(WithWeavingToFinal wav) ->
  WithWeavingToFinal @m $ \s wv ins -> do
    Compose st <- liftBaseWith $ \lower -> do
      initST <- lower (pure ())
      wav
        (Compose $ StMF (\(_ :: ()) -> s) initST)
        (\(Compose st) ->
          (Compose . StMF id) <$> lower (runStMF st >>= wv)
        )
        (inspectStMF ins' . getCompose >=> ins)
    runStMF st
{-# INLINE finalToFinalBaseControl #-}
```

**Comment by adamConnerSax** [comment]
Thanks!  I don't think I want to insist on MonadBaseControl either, though I haven't thought about it much.  It'd probably be fine.  I can see it's a pretty easy constraint to satisfy for most ordinary stacks.
But I think I'd rather just find some way to catch the error and throw it so that it gets reported.  
Though maybe the extra stability of the ```Final``` version would be worth it...
