### ISSUE TITLE
Performance of polysemy depends on loopbreaker

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#324]
Polysemy's claimed performance gains in 8.10 are a combination of the specialization work, enabling the polysemy-plugin, and https://github.com/polysemy-research/loopbreaker being enabled. Currently loopbreaker is disabled in HEAD, and I can't remember if it was ever working. @TheMatten do you know?

I'm happy to throw some elbow juice at this if y'all are too busy.

**Comment by TheMatten** [comment]
I think it did.
Go for it if you want, not sure when I'll find some time to look into it.

**Comment by KingoftheHomeless** [comment]
I've been busy for the month, and will continue to be in march. I'd appreciate support!
