### ISSUE TITLE
Running Resource before Error does not call finalizer

### ISSUE THREAD

**Issue by cah6** [polysemy-research/polysemy#325]
I recently found a program bug that manifested itself similar to https://github.com/polysemy-research/polysemy/issues/262, though it was due to the order of my interpreters being applied.

For instance, with the program:
```
testSem
  :: ( P.Member P.Resource r
     , P.Member (P.State Text) r
     , P.Member (P.Error (Maybe ())) r
     )
  => P.Sem r Text
testSem = do
  _ <- P.bracketOnError
    (P.put "init")
    (\_ -> P.put "finalized") $ \_ -> do
      P.put "before throw"
      P.throw $ Just ()
      P.put "after throw"
      return ()
  i <- P.get @Text
  return i
```

if you run it with:
```
testProgram = testSem
  & P.runError
  & P.runResource
  & P.runState ""
  & P.run
```
the result is the expected `("finalized",Left (Just ()))`. But if you run it with error and resource flipped:
```
testProgram = testSem
  & P.runResource
  & P.runError
  & P.runState ""
  & P.run
```
the result is `("before throw",Left (Just ()))`.

Perhaps this was expected, but it's pretty subtle and can result in issues if you don't know it, so I just wanted to post this in case somebody else runs into it.

I'd also like to ask if there's a preferable way around this; one possible solution I found (that I might implement locally) is to redefine `runResource` to assert that there's no error effect in the stack: if you have a `type family TElem x xs :: Bool` that checks if x is an element of the type-level list xs, you can have:
```
runResource
  :: TElem (P.Error e) r ~ 'False
  => P.Sem (P.Resource ': r) a
  -> P.Sem r a
runResource = Polysemy.runResource
```
which throws a type error in the "bad" case, but might not be the best general solution.

**Comment by Heimdell** [comment]
Yes, this is expected. In case of MTL resources use `MonadMask` capabilities of base monad (= last effect) - `IO` or `Catch`, therefore event like this is not observed. However, if you shove `EitherT` inside `CatchT` it will do the same thing.
