### ISSUE TITLE
How can you get local state?

### ISSUE THREAD

**Issue by bmabsout** [polysemy-research/polysemy#329]
Hello, (Disclaimer: I am new to the polysemy world)
I was wondering if there's a general way to get local state with the state effect. In my case, I got the special case written below working but I was wondering if this can be done more generally (here using `evalState` means I am sticking to a pure interpretation and it forces me to have `State` be the first effect in the stack). is creating a new effect with a Forget command the right way to do this?

Thanks

```haskell
forget :: Sem (State s:r) a -> Sem (State s:r) a
forget m = get >>= \currState -> evalState currState m & raise

local :: (s -> s) -> Sem (State s:r) a -> Sem (State s:r) a
local modifier s = modify modifier >> forget s
```

**Comment by KingoftheHomeless** [comment]
I'd just do:
```haskell
local :: Member (State s) r => (s -> s) -> Sem r a -> Sem r a
local f m = do
  s <- get
  put (f s)
  a <- m
  put s
  return a
```
Or is there a reason that wouldn't work?

**Comment by bmabsout** [comment]
Hmm, I can't believe I missed such a simple solution! It should definitely work, Thank you!
