### ISSUE TITLE
Documentation for creating new effects by composing existing ones

### ISSUE THREAD

**Issue by expipiplus1** [polysemy-research/polysemy#334]
Often in MTL code it's nice to create an new effect by composing some existing ones, wrapped in a newtype to hide implementation details; something like `newtype MyMonadT m a = MyMonadT (ExceptT Foo (StateT Bar m) a)`. One then goes on to derive and write a bunch of instances.

I couldn't find any documentation on how to do something similar in Polysemy, but it seems like being able to create such effects compositionally would be a handy thing. The two biggest benefits are implementation hiding, and guaranteeing order of effects.

I suppose the interpret function for the example above would require the user to specify how `State` and `Error` are interpreted.

**Comment by googleson78** [comment]
Perhaps [Bundle](https://hackage.haskell.org/package/polysemy-1.3.0.0/docs/Polysemy-Bundle.html) could be helpful?

**Comment by expipiplus1** [comment]
Bundle is exactly what I was looking for. Thanks @googleson78!
