### ISSUE TITLE
Build failure on GHC 8.10 (win64)

### ISSUE THREAD

**Issue by ahri** [polysemy-research/polysemy#336]
I'm following along some blog posts and saw that 8.10 is when we get cost-free polysemy abstractions, so I dutifully grabbed it, and cabal, and manually fixed up my path, got `polysemy` installed and imported into a `ghci` session, but when installing the plugin I got the following errors:

    > cabal install --lib polysemy-plugin

    Preprocessing library for polysemy-plugin-0.2.5.0..
    Building library for polysemy-plugin-0.2.5.0..
    [1 of 7] Compiling Paths_polysemy_plugin ( dist\build\autogen\Paths_polysemy_plugin.hs, dist\build\Paths_polysemy_plugin.o )
    [2 of 7] Compiling Polysemy.Plugin.Fundep.Stuff ( src\Polysemy\Plugin\Fundep\Stuff.hs, dist\build\Polysemy\Plugin\Fundep\Stuff.o )
    [3 of 7] Compiling Polysemy.Plugin.Fundep.Unification ( src\Polysemy\Plugin\Fundep\Unification.hs, dist\build\Polysemy\Plugin\Fundep\Unification.o )
    
    src\Polysemy\Plugin\Fundep\Unification.hs:133:23: error:
        Not in scope: type constructor or class `Ct'
        |
    133 |     -> [(Unification, Ct)]
        |                       ^^
    
    src\Polysemy\Plugin\Fundep\Unification.hs:134:25: error:
        Not in scope: type constructor or class `Ct'
        |
    134 |     -> ([Unification], [Ct])
        |                         ^^
    cabal: Failed to build polysemy-plugin-0.2.5.0. See the build log above for
    details.

_Edit: I tried checking this repo out @ 016c16fbb1b57a0d728e57e2cf8e36453e8edd8d thinking the version in Hackage might be different, but I got the same result._

**Comment by jgrosso** [comment]
I can also repro this.

**Comment by googleson78** [comment]
Should work now (I haven't really tested on a win machine, but I would be surprised if it doesn't)

**Comment by googleson78** [comment]
Actually let's keep this open, since this is not on Hackage yet.

**Comment by ahri** [comment]
Can confirm it works on Windows 10 now :)

**Comment by cumber** [comment]
Would be great if we could get a Hackage release supporting GHC 8.10

**Comment by galagora** [comment]
Hey @TheMatten or @KingoftheHomeless, could we please get a Hackage release? The 336-build-with-810 doesn't really contain any changes relative to the previous version, so it should just be a version bump and upload of the source tarball.

**Comment by KingoftheHomeless** [comment]
This went flying right past my head for some reason. I I think we should go for a v1.4 release, since some other compatibility fixes are spread across the commts. @TheMatten I'm a bit busy at the moment, so could you get on this? Otherwise, I will be able to put together a new release at the very latest sometime during the weekend.

**Comment by galagora** [comment]
Could you possibly upload the plugin update now, though? There aren't really any changes from the last version. You can even use [my tarball](https://github.com/galagora/polysemy/releases/tag/v0.2.5.1-plugin).

**Comment by KingoftheHomeless** [comment]
True, `polysemy-plugin` should be enough! It'll be up in the hour.

**Comment by KingoftheHomeless** [comment]
`polysemy-plugin` 0.2.5.1 released on Hackage.

This sort of nudging is really important, and I very much encourage and appreciate it! Especially if it's an issue where the solution has already been implemented, and just not made available.
