### ISSUE TITLE
Trouble implementing timeout

### ISSUE THREAD

**Issue by sorki** [polysemy-research/polysemy#342]
I've tried implementing timeout effect but having a hard time writing interpreters for it. Closest I've got is this attempt trying to throw an error instead of working around maybe but the error is thrown instantly. Pointers welcome!

```haskell
data Timeout m a where
  Timeout :: Int -> m a -> Timeout m (Maybe a)

makeSem ''Timeout


runTimeoutErr :: (Member (Embed IO) r, Member (Error String) r)
               => Sem (Timeout ': r) a
               -> Sem r a
runTimeoutErr m = withLowerToIO $ \lower _fin -> lower $ interpretH \case
  Timeout ts a -> do
    ma <- runT a
    e <- raise (throw "ZZ")
    ins <- getInspectorT
    z <- embed $ System.Timeout.timeout (ts * 1_000_000) $ lower $ runTimeoutErr ma
    pureT $ maybe (e) (id) <$> fmap (inspect ins) z
```

**Comment by bolt12** [comment]
Hi, I have a working `Timeout` effect:

```haskell
import Control.Monad
import Data.Functor
import Polysemy
import Polysemy.Final
import qualified System.Timeout as T

data Timeout m a where
  Timeout :: Int -> m a -> Timeout m (Maybe a)

makeSem ''Timeout

runTimeoutToIO :: Member (Final IO) r => Sem (Timeout ': r) a -> Sem r a
runTimeoutToIO =
  interpretFinal
    ( \case
        Timeout i ma -> do
          n <- pureS Nothing
          ma' <- T.timeout i <$> runS ma
          pure $ ma' >>= maybe n (pure . fmap Just)
    )
```

I think @TheMatten at the time said to me that `Final` should be used but I don't quite remember the details, maybe he can expand on that here for posterity! You can maybe tweak this implementation to your fit :)

**Comment by sorki** [comment]
Thank you!! I've had one attempt using `Final` but had problems with it due to my poor understanding of `Tactictal / Strategical`.

Interested to know the reason for `Final`.

Btw would you consider PRing this for `polysemy-zoo`?

**Comment by sorki** [comment]
@bolt12 I've did one change to your runner so it doesn't require `polysemy-plugin`

`s/interpretFinal/interpretFinal @IO/`

**Comment by bolt12** [comment]
Sure, feel free to make any modifications that suit you! I don't know if it's worth it to submit a PR with this effect to the `polysemy-zoo` since it is so small, but I might be wrong!

**Comment by TheMatten** [comment]
@bolt12 Sorry, I missed this conversation - difference basically is that `Strategic` gives you access to final monad (`IO`) wrapped around opaque state `f` in threaded action, which we need to satisfy type of `timeout`s argument (`IO a`). On the other hand, `Tactical` only gives you `f a` - attempt to lift it into `IO` with `pure` wouldn't help, because action would already be evaluated at that point.

**Comment by sorki** [comment]
Thanks again, now part of https://github.com/sorki/polytype/blob/master/src/Polytype/Timeout.hs with slight modifications to go with my polymorphic Delay effect.

**Comment by bolt12** [comment]
Awesome!
