### ISSUE TITLE
Move plugin under main `polysemy` package

### ISSUE THREAD

**Issue by TheMatten** [polysemy-research/polysemy#351]
Having plugin as a separate package allows users to enable incompatible versions of libraries, creating confusing errors, and makes it possible to get them out of sync e.g. on Stackage. `polysemy` is meant to be used with plugin anyway - if there're situations where `polysemy` compiles and plugin does not (like modified GHC), we could provide flag that disables relevant code using `CPP`.

**Comment by googleson78** [comment]
This would effectively kill off any hope for having plugin enabled while working on polysemy itself, right?

**Comment by isovector** [comment]
Yeah, but I think that's never going to happen anyway.
