### ISSUE TITLE
Plugin breakage on recursion

### ISSUE THREAD

**Issue by sorki** [polysemy-research/polysemy#355]
Enabling plugin causes `echo` which calls itself to produce GHC panic.

Reproducer https://github.com/sorki/polytype/commit/d1994a2ededfc14142fa8bba3be8247aae3b905d

Relevant function https://github.com/sorki/polytype/blob/d1994a2ededfc14142fa8bba3be8247aae3b905d/src/Polytype/Teletype.hs#L138-L153

Another reproducer - this one only fails when the functions are given type annotations (plugin already enabled) https://github.com/sorki/polytype/commit/7668a4273ffe7034e9ac999473223d8e5a621865

Edit: GHC 8.10.1

**Comment by isovector** [comment]
Fixed in latest afaict.
