### ISSUE TITLE
Plugin panics tracking issue

### ISSUE THREAD

**Issue by sorki** [polysemy-research/polysemy#356]
GHC 8.10.1 related

- https://github.com/polysemy-research/polysemy-zoo/issues/65
- #354 
- #355

For most of my lib I've switched to enabling plugin for only few modules via `pragma` instead of enabling it globally. 

What's interesting is that this only manifests on full builds via `cabal build` but not in `cabal repl`.

**Comment by adamConnerSax** [comment]
On 8.10.2 it manifests for me (sometimes, anyway) in ```cabal new-repl``` as well.

**Comment by googleson78** [comment]
Anyone with some comparatively minimal reproducer? I'm not using 8.10 and so haven't gotten any panics :/ (at least not ones that weren't caused by non-compiling code)

**Comment by TheMatten** [comment]
@sorki you can try https://github.com/polysemy-research/polysemy/pull/382

**Comment by tek** [comment]
can confirm that the panic in #354 doesn't occur anymore.

**Comment by isovector** [comment]
Closing this. Feel free to reopen if you think it's still an issue.
