### ISSUE TITLE
Update readme with more accurate performance and comparison details

### ISSUE THREAD

**Issue by AlistairB** [polysemy-research/polysemy#358]
I use both fused effects and polysemy. I like both for different reasons. I recommend polysemy in many cases.

However, polysemy does not seem to be very accurate about its claims of performance in the readme. These claims seem to be the initial goals and beliefs about performance, that have not actually been realised? 

Both @lexi-lambda's [talk](https://www.youtube.com/watch?v=0jI-AlWEwYI) and @isovector [blog post](https://reasonablypolymorphic.com/blog/mea-culpa/) suggest that polysemy is in fact 'slow' in many? cases.

I think the fused effects readme is pretty reasonable here when comparing itself with polysemy.

> Like polysemy, fused-effects is a batteries-included effect system capable of scoped, reinterpretable algebraic effects.

> As of GHC 8.8, fused-effects outperforms polysemy, though new effects take more code to define in fused-effects than polysemy (though the Control.Carrier.Interpret module provides a low-friction API for rapid prototyping of new effects). Like freer-simple and unlike fused-effects, polysemy provides custom type errors if a given effect invocation is ambigous or invalid in the current context.

Specifically the following claims seem to be questionable.

- `polysemy is a library for writing high-power, low-boilerplate, zero-cost, domain specific languages` - is it really zero cost?
- `It's like mtl but composes better, requires less boilerplate, and avoids the O(n^2) instances problem.` - does it have the same performance as mtl then?
- `It's like freer-simple but more powerful and 35x faster.` - is this 35x accurate?
- `It's like fused-effects but with an order of magnitude less boilerplate.` - I think the `order of magnitude` bit is slightly overstated. Does that mean it takes 1/10th of the code in polysemy to work with effects? (You could possibly argue this as fused effects has some edge cases that require a lot of boilerplate. On another note I think fused effects is more complex to learn + use where polysemy is very intuitive). And again, does this mean polysemy is as fast as fused effects?
- `Effects are zero-cost, meaning that GHC1 can optimize away the entire abstraction at compile time. 1: Unfortunately this is not true in GHC 8.6.3, but will be true in GHC 8.10.1.` - Is it true the polysemy is zero cost in ghc 8.10.1 ?
- The `Stellar Engineering - Aligning the stars to optimize polysemy away - Several things need to be in place to fully realize our performance goals` seems to imply these steps make it zero cost, is that true?

I hope this is not seen as inflammatory! :sweat_smile: I just think that accuracy (if it is indeed inaccurate) here is better for everyone involved in polysemy, other effect libraries and the wider Haskell community.

**Comment by TheMatten** [comment]
Yeah, we're planning to change that README - I guess the reason why it's not done yet is that people were busy with other stuff, plus we're figuring out future direction when it comes to underlying implementation.

**Comment by avanov** [comment]
Hi, I'd like to know why the section about Polysemy plugin being helpful in performance improvement was removed from the readme? I've also left a similar comment on https://www.reddit.com/r/haskell/comments/h99voy/polysemy_mea_culpa_reasonably_polymorphic/fzjgfjf?utm_source=share&utm_medium=web2x as I'd like to clarify the actual impact of the plugin to the presented benchmark. I'd appreciate your feedback.

**Comment by TheMatten** [comment]
One of the requirements for optimizations to work properly was [`loopbreaker`](https://github.com/polysemy-research/polysemy/issues/324), which was broken at the time AFAIK. It's a pretty "hacky" solution, plus now we know that in won't work in general anyway because of module boundaries. But assuming you had working `loopbreaker` (or did it's work manually) and had other optimizations enabled, then `polysemy` should be able to compete with reference implementation in a single-module benchmark. Though this isn't really relevant anymore, now that it seems we're going to choose different implementation strategy anyway.

**Comment by avanov** [comment]
Hi @TheMatten , thanks for your comment.  I've had some pleasant experience with Polysemy on my toy projects and it worked just fine, but if the library is going to be rewritten, would you personally recommend choosing Polysemy for a new greenfield IO-bound business-critical project at this point? I'm mostly looking for stability of interfaces and incremental improvements (including performance), and more flexibility compared to mtl and transformers.

**Comment by TheMatten** [comment]
Polysemy v2 will surely have breaking changes, though goal is to preserve most of the API, doing changes where needed or to fix inconsistencies in current one. I really wonder though what will future steps of other effects libraries look like - they can either decide that current performance is good enough, or decide to do the same thing as us - switching implementation at cost of making breaking changes. So, to your original question, if you really depend on stable interface, it's hard to make guarantees about v2, but if you're okay with doing v2 switch which may be accomplishable with something like [`retrie`](https://hackage.haskell.org/package/retrie), then it may work for you.

**Comment by avanov** [comment]
Thanks!
