### ISSUE TITLE
Memory leak with Applicative (*>)

### ISSUE THREAD

**Issue by goertzenator** [polysemy-research/polysemy#368]
I have a program that uses Polysemy and Streaming, and we've observed a memory leak when using the Streaming function `mapM_`.  When this function is pulled into my code, I can fix the leak by changing `*>` to `>>`.  Shouldn't these two operators do the same thing for `Sem`?

``` Haskell
myMapM_ :: Monad m => (a -> m b) -> Stream (Of a) m r -> m r
myMapM_ f = loop where
  loop str = case str of
    Return r       -> return r
    Effect m       -> m >>= loop
    Step (a S.:> as) -> f a >> loop as -- older impl, doesn't leak
 -- Step (a S.:> as) -> f a *> loop as -- newer impl, leaks!
```

The heap plot using `>>` looks like...
![image](https://user-images.githubusercontent.com/605072/88592460-ab06be00-d023-11ea-8cfe-fbaa34327460.png)

... and the heap plot using `*>` looks like...

![image](https://user-images.githubusercontent.com/605072/88592935-6596c080-d024-11ea-9dfc-2c9be6422dae.png)

**Comment by KingoftheHomeless** [comment]
This is probably due to `Sem`'s `Applicative` instance relying on the default implementations of `*>` and `<*`.

I'd welcome a small pull request that adds the following under `instance Applicative (Sem r)` in `Polysemy.Internal`:

```haskell
liftA2 f ma mb = Sem $ \k -> liftA2 (runSem ma k) (runSem mb k)

ma <* mb = Sem $ \k -> runSem ma k <* runSem mb k

ma *> mb = Sem $ \k -> runSem ma k *> runSem mb k
```
Alternatively, many monads are bad at optimizing `*>`, (the default implementation is _really_ slow if `(<*>)` is defined as `ap` for the underlying monad), so the above definition may not be safe enough. An alternative is using:

```haskell
ma *> mb = Sem $ \k -> runSem ma k >>= \_ -> runSem mb k
```
Which is guaranteed to perform as good as `>>=`.

If you have the patience to fork `polysemy`, test out the changes and see if it makes a difference. Otherwise, a pull request with the former definitions are probably good enough.

**Comment by goertzenator** [comment]
Thanks, these additions seem to work and I'll do a PR.  Any objection to just defining `*>` as...

``` haskell
(*>) = (>>)
```

**Comment by KingoftheHomeless** [comment]
Yeah, [monad of no return.](https://gitlab.haskell.org/ghc/ghc/-/wikis/proposal/monad-of-no-return). Honestly, we shouldn't define `return = pure` either.

**Comment by goertzenator** [comment]
Well, my reasoning is as follows: The original safe formulation (`ma *> mb = Sem $ \k -> runSem ma k >>= \_ -> runSem mb k`) uses a Monad method (`>>=`).  The short formulation (`(*>) = (>>)`) also uses a Monad method, so in my mind both are coupling equally to the Monad instance, but the short formulation seems to easily reduce some code duplication.  So my question is.. is there some performance or functionality disadvantage to the short formulation?

**Comment by KingoftheHomeless** [comment]
The disadvantage is monad of no return. Eventually, `>>` won't be a method of `Monad`, but rather, a synonym for `*>`. Writing `(*>) = (>>)` isn't future-proof.

**Comment by goertzenator** [comment]
I understand now, thanks!  I will stick with your safe formulation.

**Comment by TheMatten** [comment]
@KingoftheHomeless:
> Alternatively, many monads are bad at optimizing `*>`, (the default implementation is really slow if `(<*>)` is defined as `ap` for the underlying monad), so the above definition may not be safe enough.

Doesn't same argument apply to `(<*)`? That is, wouldn't it make sense to use `(>>=)` in it's implementation too?:
```hs
ma *> mb = Sem $ \k -> runSem ma k >>= (runSem mb k $>)
```

**Comment by KingoftheHomeless** [comment]
Eh, it's not as critical. `<*` is much rarer, and the gains aren't as big.
For comparison, assuming everything is defined in terms of `liftM` and `ap`:

```haskell
   ma >>= (<$ mb)
== ma >>= \a -> mb >>= \_ -> return a
```

```haskell
   liftA2 const ma mb
== liftM const ma `ap` mb
== (ma >>= return . const) >>= \f -> mb >>= \b -> return (f b)
```
So its two uses of `>>=` compared to three (with the safe implementation of `*>`, it's one use of `>>=` compared to three).
At that point, I'd prefer leaving the opportunity open for underlying monads to optimize `<*` (or `liftA2`).
