### ISSUE TITLE
Blocking runT/getInitialStateT if called from thread?

### ISSUE THREAD

**Issue by alaendle** [polysemy-research/polysemy#373]
It might be obvious for insiders why this doesn't work as expected - however I wonder why this code isn't able to execute the callback.

It just prints:

```
Subscribe: 1
Subscribe: 2
Before runT
Before runT
```

```haskell
nestedImpl :: Int -> (String -> (Bool -> IO ()) -> IO ()) -> IO ()
nestedImpl i cb =
  void $ forkIO $ do                            -- if this isn't forked everything works as expected.
    threadDelay $ 1 * 1000 * 1000
    cb (show i) (\b -> putStrLn $ "result " ++ show b)

data Broker m a where
  Subscribe :: Int -> (String -> m Bool) -> Broker m ()

makeSem ''Broker

runBroker :: Member (Embed IO) r => Sem (Broker : r) a -> Sem r a
runBroker = interpretH $ \case
  Subscribe channel cb -> do
      embed $ putStrLn ("Subscribe: " ++ show channel)
      withLowerToIO $ \lower finish -> nestedImpl channel (\s icb -> do
        eff <- lower $ do
          embed $ putStrLn "Before runT"
          cbc <- runT $ cb s
          embed $ putStrLn "After runT"
          raise $ runBroker cbc
        ins <- lower getInspectorT
        icb $ fromMaybe False $ inspect ins eff
        finish)
      pureT ()

prog :: Members '[Broker, Embed IO] r => Sem r ()
prog = do
  subscribe 1 (\_ -> pure True)
  subscribe 2 (\_ -> pure False)
  embed $ threadDelay $ 10 * 1000 * 1000

runAllEffects :: (forall r. Members [Broker, Embed IO] r => Sem r a)
              -> IO a
runAllEffects program =
  program
    & runBroker
    & embedToFinal @IO
    & runFinal
```

If the `forkIO` is removed everything works as expected. Maybe this issue is related to https://github.com/polysemy-research/polysemy/issues/211 - since I crossed the problem originally using a C/FFI callback (that might also be raised from a different thread).

For now I keep short; since my hope is that the underlying problem is obvious to some more experienced developers. But please don't hesitate to contact me if I could clarify things or can otherwise contribute.

**Comment by alaendle** [comment]
Without understanding the consequences I guess that this might be a solution:

```haskell
runBroker :: Member (Embed IO) r => Sem (Broker : r) a -> Sem r a
runBroker m = withLowerToIO $ \lower _ -> lower $ interpretH (\case
  Subscribe channel cb -> do
    embed $ putStrLn ("Subscribe: " ++ show channel)
    ins <- getInspectorT
    cb' <- bindT cb
    let run = runBroker . cb'
    is <- getInitialStateT
    embed $ nestedImpl channel (\s icb -> do
        putStrLn "Before runT"
        eff <- lower $ run (s <$ is)
        putStrLn "After runT"
        icb $ fromMaybe False $ inspect ins eff)
    pureT ()) m
```

**Comment by alaendle** [comment]
Guess https://github.com/polysemy-research/polysemy/issues/63#issuecomment-495757304 might point the right direction - I will implement/verify this approach as soon as I find some spare time. 

Its really sad that there are so man patterns around all trying to solve more or less various variants of a 'callback problem'. As far as I get it `withLowerToIO` should be used with care - and never in async scenarios (https://github.com/polysemy-research/polysemy/issues/205, right?, not sure if `asyncToIOFinal ` is safe it that sense). 

In any case, a more beginner friendly API that makes it harder to shoot yourself in the foot would be nice; also I wonder if it is to hard to prepare some convenience functions handling most of this tedious boilerplate code that is needed for a callback. 

At least my perception is that a lot of issues (old and new 😄) involve callback topics. 

I will post an update once I gained further insights...

**Comment by alaendle** [comment]
As promised an update - and I hope this could help other users as well...

Adopting the pattern from https://github.com/polysemy-research/polysemy/issues/63#issuecomment-495757304 led me to 
```haskell
runBrokerIO
  :: forall r a.
     Member (Embed IO) r => (forall x. Sem r x -> IO x)
  -> Sem (Broker ': r) a
  -> Sem r a
runBrokerIO r = interpretH $ \case
  Subscribe channel f -> do
    is <- getInitialStateT
    ins <- getInspectorT
    f' <- bindT f
    embed $ nestedImpl channel $ \msg icb -> do
      res <- r .@ runBrokerIO $ f' (msg <$ is)
      icb $ fromMaybe False $ inspect ins res
    pure is
```

This seems to work and compose fine, but feels quite unhandy since you need to specify the lowering interpreters. This might be an advantage for some use cases, but my guess is that normally that just creates additional boilerplate code. So I switched to `Final IO`.

```haskell
runBrokerIO2
  :: forall r a.
     Member (Final IO) r => Sem (Broker ': r) a -> Sem r a 
runBrokerIO2 = interpretFinal @IO $ \case
  Subscribe channel f -> do
    is <- getInitialStateS
    ins <- getInspectorS
    f' <- bindS f
    liftS $ nestedImpl channel $ \msg icb -> do
      res <- f' (msg <$ is)
      icb $ fromMaybe False $ inspect ins res
```

This solution feels better - and at least is my new pattern to encapsulate external systems/libraries. The only drawback I see so far is that (by-design) you couldn't use other effects during interpretation (which is very handy if you want to include logging/tracing). But this could be seen also as an advantage, because it enforces a clear separation of concerns - but also adds immense complexity if really needed.

**Comment by tek** [comment]
what's the `nestedImpl` in your real-world application?

**Comment by alaendle** [comment]
@tek: Thanks for asking; I thought it doesn't matter, but I should have provided more context. 
As always real world is complicated - so `nestedImpl` has the signature 
```haskell
subscribeQueue :: Client -> String -> (String -> (Bool -> IO ()) -> IO ()) -> IO (() -> IO ())
```
It's implementation is _only_ an adapter to a proprietary messaging library (using inline-c to capture the C API). 

But I guess it's not worth to focus on it's implementation details. Since it is open source and should expose the same characteristics  just think you like to create an effect for an AMQP message broker and take a look at:
```haskell
consumeMsgs :: Channel -> Text -> Ack -> ((Message,Envelope) -> IO ()) -> IO ConsumerTag
```
(documentation: https://hackage.haskell.org/package/amqp-0.20.0/docs/Network-AMQP.html#v:consumeMsgs)

So at least for my use case the problem was that I didn't know how to handle such a callback (multiple asynchronous invocations in different thread) in conjunction with polysemy. Please let me know if you are interested in further details.

And please remind the disclaimer I already made 😉 
> [...] So maybe my design approach is simple wrong, and doesn't make sense in terms of an effect system? To be honest I tried to substitute the simple ReaderT-pattern with polysemy, and at a first glance I was happy to avoid a lot of boilerplate code. [...] Maybe me level of haskell knowledge is just not sufficient [...]

**Comment by tek** [comment]
yeah, just wondering how restrictive your requirements are.
have you considered moving `nestedImpl` out of the interpreter and using the forklift to create a `Sem` wrapper?

**Comment by alaendle** [comment]
@tek Interesting idea/concept; haven't thought about something like this; to be honest I have no feeling how this would affect the design - so to make are more substantiated statement I'll need to implement this approach and gain some deeper insight about the pros and cons (have I mentioned that I'm a Haskell beginner? 😉 ). 

Do you have a reference where this approach is used in a similar way, so that I can get some inspiration? I just read through https://apfelmus.nfshost.com/blog/2012/06/07-forklift.html and visited https://github.com/polysemy-research/polysemy/blob/4a5f2ce92a752cfbf96ae8a31ee12b100e2c0482/src/Polysemy/Internal/Forklift.hs#L32, but maybe there is a cleaner example?

**Comment by tek** [comment]
I'm just basing this on my own general experience with higher-order interpreters (see for example https://funprog.zulipchat.com/#narrow/stream/216942-Polysemy/topic/wrap.20higher-order.20effect/near/191684600 ), fighting endlessly with the types while just moving logic outside of the interpreter presents a trivial solution.

You already used the forklift in one of your attempts (`withLowerToIO`), so I just wondered whether you could move that part to a separate function and blackbox it.

**Comment by alaendle** [comment]
@tek: Unfortunately I couldn't access your conversation on zulipchat (corporate firewall 🙈 ), but I think I got the idea nonetheless. Since I'm unwilling to move `nestedImpl` out of the interpreter, because I want the callback to execute other effects without dividing the DSL, I see the forklift more or less leave me the same advantages/disadvantages of providing a custom lowering function - as `runBrokerIO` in https://github.com/polysemy-research/polysemy/issues/373#issuecomment-679897312. Because if I've understood the idea, that's exactly where the forklift is used to move out the execution/interpretation of the callback - but that means that somewhere I need to define what/how to execute. Or maybe I just got it all wrong?

**Comment by tek** [comment]
not sure what you mean by "dividng the DSL", why would you not be able to execute other effects?

**Comment by alaendle** [comment]
@tek Please excuse my late response, but I wanted to implement the forklift first to validate my assumptions and be able to give a substantial feedback. To be honest the picture is still not complete clear now. I see advantages/disadvantages in any possible solution. 

First the bonus of the forklift - you could throw all the strategy/tactics stuff away 😉 and it makes the fact that no state is shared between callback code and the rest obvious. Also you could include other effects in the interpretation in a good way.

But even if I was unclear or just formulated it wrong; I still see some forklift-drawbacks - you need to make the effects that the forklift can handle and how it handles them explicit - e.g. from my code `fl <- newForkLift (runM . runLog)` and `Subscribe :: Int -> (String -> Sem '[Log, Embed IO] Bool) -> Broker m ()`. However I would agree that this simple reflects the inner connection - since there is nothing shared (!) - and that this is somehow more clear and safe from an API standpoint. Otherwise you could spread an effect across the callback and the rest of the code that relies on common state/interpretation and that just couldn't work (o.k. nothing stops you to do so in the forklift scenario, but at least the definition of the forklift and it's usage in the interpreter point to the right direction - and the fact that you need to add the interpreter for a new effect at least on two places) - and that was the point I wanted to make by saying that this is "dividing the DSL".

So until I see good reason to switch I will stick with the `interpretFinal @IO`-solution; just because of it's simplicity/safety - even if the interpreter couldn't make use of other effects. Maybe I need to come up with something that at least enables common logging.

**Comment by tek** [comment]
right, sounds reasonable!

**Comment by alaendle** [comment]
Many thanks; I think the topic has been examined in detail and that's why I'm closing this issue now. I really hope that it might help others with similar requirements.

Special thanks to @tek for pointing me to the forklift pattern.

So at least I've learned a lot about the inner workings and API of polysemy and explored the forklift pattern (unknown to me).
