### ISSUE TITLE
polysemy-plugin seems like it participates in a GHC panic under very specific circumstances

### ISSUE THREAD

**Issue by Ptival** [polysemy-research/polysemy#374]
I apologize for the vagueness here but this is quite a hairy situation.

I was getting GHC panics when trying to run haskell-ide-engine (HIE):
```
"panic! (the 'impossible' happened)\n  (GHC version 8.8.3 for x86_64-unknown-linux):\n\tplusSimplCount\n\nPlease report this as a GHC bug:  https://www.haskell.org/ghc/reportabug\n"
```

After a lot of tinkering, this seems to happen only when:
- I'm using polysemy-plugin with the GHC option `-fplugin=Polysemy.Plugin`,
- and it is run by `hie`/`hie-wrapper`. Things otherwise build fine. Only when running HIE do I get the GHC panic...

Reproducible nix environment (using Haskell.nix):
https://github.com/Ptival/segfaulty

Here's my `ghc-pkg list` in said environment (I believe it also happens when I force `Cabal >= 3.2.0.0`):

```
/nix/store/18nag263l4xizsvcr40f2nakyxlhpp59-ghc-shell-for-segfaulty-ghc-8.8.3-env/lib/ghc-8.8.3/package.conf.d
    Cabal-3.0.1.0
    QuickCheck-2.14.1
    array-0.5.4.0
    async-2.2.2
    atomic-primops-0.8.3
    base-4.13.0.0
    binary-0.8.7.0
    bytestring-0.10.10.0
    containers-0.6.2.1
    deepseq-1.4.4.0
    directory-1.3.6.0
    filepath-1.4.2.1
    first-class-families-0.8.0.0
    ghc-8.8.3
    ghc-boot-8.8.3
    ghc-boot-th-8.8.3
    ghc-compact-0.1.0.0
    ghc-heap-8.8.3
    ghc-prim-0.5.3
    ghc-tcplugins-extra-0.3.2
    ghci-8.8.3
    hashable-1.3.0.0
    hpc-0.6.0.3
    integer-gmp-1.0.2.0
    mtl-2.2.2
    parsec-3.1.14.0
    polysemy-1.3.0.0
    polysemy-plugin-0.2.5.0
    pretty-1.1.3.6
    primitive-0.7.1.0
    process-1.6.8.0
    random-1.2.0
    rts-1.0
    splitmix-0.1.0.1
    stm-2.5.0.0
    syb-0.7.1
    template-haskell-2.15.0.0
    terminfo-0.4.1.4
    text-1.2.4.0
    th-abstraction-0.3.2.0
    time-1.9.3
    transformers-0.5.6.2
    type-errors-0.2.0.0
    type-errors-pretty-0.0.1.1
    unagi-chan-0.4.1.3
    unix-2.7.2.2
    xhtml-3000.2.2.1
```

**Comment by googleson78** [comment]
Did you try using some other ghc plugins with the same setup?

**Comment by Ptival** [comment]
Nope. I guess I could try Liquid Haskell since it just went GHC plugin. Do you know any other GHC plugin that'd be easy to try?

**Comment by googleson78** [comment]
Here's some:
https://github.com/tfausak/splint
https://github.com/ndmitchell/record-dot-preprocessor
https://github.com/clash-lang/ghc-typelits-natnormalise

**Comment by isovector** [comment]
Closing due to age; feel free to open if it still is happening.
