### ISSUE TITLE
Async effect leaks implementation detail (and therefore prevents pure interpretation)

### ISSUE THREAD

**Issue by alaendle** [polysemy-research/polysemy#378]
This is more something that could be discussed - I really wonder why the Async effect presents `Control.Concurrent.Async.Async` in it's API. This offers potential misuse by e.g. directly awaiting the result; so from my perspective I would favour the encapsulation into a type that just represents a simple handle and couldn't be used by the client otherwise.

The other improvement this might offer is that it might be possible to interpret the Async effect in a pure way. My guess is that nothing contradicts that everything inside async is interpreted immediately as async gets interpreted, and wait just returns this result.

So please don't get me wrong, I just stumbled across this question and was wondering why things are as they are. In no way did I want to criticize. Also I should mention that I'm relatively new to FP and my point of view corresponds to a simple polysemy user with an strong OOP background; so maybe my assumptions are just wrong. I'm really looking forward to learn by hearing other peoples opinion.

**Comment by tek** [comment]
absolutely reasonable! in my opinion it should be `Async handle :: Effect`. This way you can still depend on the concrete implementation.

**Comment by tek** [comment]
mh, probably `(handle :: * -> *)`

**Comment by tek** [comment]
created a pull request to showcase how it would look.

**Comment by adamConnerSax** [comment]
Question, though I'm not sure it's yet coherent:
I've got a library that uses polysemy to provide a set of useful effects (Pandoc doc writing, caching, unique-id generation, logging) for building data-driven html.  I also expose/wrap async so I can do concurrent computations when building analysis-heavy documents.  Are you suggesting that I should rather create an effect to which I can submit computations-- which need to all be complete before continuing--and then choose in the interpretation stage if that effect uses async or not?  
I think that makes sense, I just want to make sure I understand.

**Comment by tek** [comment]
I would assume that `sequenceConcurrently` is the main reason for this issue, so abstracting that would probably be the most sensible solution

**Comment by tek** [comment]
parallelism and asynchronicity are quite different from the modeling perspective, but in Haskell I guess they are notoriously underspecified

**Comment by adamConnerSax** [comment]
Yes, ```sequenceConcurrently```!
And I do vaguely understand that parallelism and asynchronicity are different. 
As both library writer and user, though, I just want a simple way to say: "Do all these things, none depends on the others, give me the results when all are done or as soon as any have failed." and then be able to do that in the fastest way possible when I so choose.  So, you're correct, it's not really async that I want, it's a rough parallelism. I'm just using async as a simple way to get there, both because that's enough in my case, and because the various tasks are often really unrelated, they just need to all be done before their results can be combined in the next stage. 
Is there a simpler/cleaner way to do that than ```sequenceConcurrently```?

**Comment by tek** [comment]
my preference would be to have something like a `Parallel` effect.
this could, for example, be implemented with streaming frameworks or libraries like https://hackage.haskell.org/package/thread-supervisor as alternatives to `Async`.
So while I agree with @KingoftheHomeless that overloading `Async` like that is unsound, I still consider it to be sensible to remove the implementation detail from the effect signature, though it's not a strong feeling.

**Comment by tek** [comment]
is `NonDet` a basis for this?

**Comment by googleson78** [comment]
I don't know if a "Parallel" effect will do the job in @adamConnerSax's case, because he wants to abort all computations as soon as one of them fails, afaiu

**Comment by tek** [comment]
I'd say that's up to the interpreter then, no?

**Comment by adamConnerSax** [comment]
I suppose a "Parallel" effect could have either different interpreters or different combinators, a "run until each is finished or has failed" and "run until each has finished or any have failed" and then the interpreters would have to be able to manage both cases?  I can actually imagine wanting both, though for me failure usually indicates a bug/data-issue that means I will have to rerun all anyway, hence the early failure.  
But I am not sure how best, and most safely, implement any of these!  Hence my quick reliance on ```sequenceConcurrently```.

**Comment by tek** [comment]
right, we could just use constructors for "fail fast" and "fail individually".

**Comment by KingoftheHomeless** [comment]
Unless there are some more convincing reasons why this is a good idea, I'll be closing this as a wontfix.

**Comment by tek** [comment]
sounds good to me

**Comment by alaendle** [comment]
> My view is that instead of trying to use `Async` in application code -- and interpret it purely for testing -- you should use other effects in application code, and interpret these using `Async`. By doing this, the application code can be tested by interpreting these other effects purely, instead.

If we see it that way I totally agree that no change is advisable. Also I'm not 100% convinced, at least not for now, that this approach is solving all problems. But since my imagination is limited, I just have to try this out when I get the chance. So from my point of view we could close this issue for now; maybe everything is fine already or I might open another issue with a more detailed notion/vision if my refactoring fails. Thanks to anybody participating in this discussion  - as always I've learned a lot and I hope I haven't taken up too much of your time.

**Comment by KingoftheHomeless** [comment]
Sounds like a plan!
