### ISSUE TITLE
Time measuring effect

### ISSUE THREAD

**Issue by L7R7** [polysemy-research/polysemy#380]
I'm currently trying to implement an effect that provides the possibility to measure the duration of a given action. The effect definition I have in mind looks like this:

```hs
data DurationObservation m a where
  ObserveDuration :: m b -> DurationObservation m b
```
The interpreter I want to write should use https://github.com/qnikst/prometheus-haskell to measure the duration and provide metrics based on the results. In particular, I want to use [`observeDuration`](https://github.com/qnikst/prometheus-haskell/blob/master/prometheus-client/src/Prometheus/Metric/Observer.hs#L23).

I came up with the following implementation:
```hs
observeDurationToIO :: (Member (Final IO) r) => Histogram -> Sem (DurationObservation ': r) a -> Sem r a
observeDurationToIO histogram = interpretFinal @IO $ \case
  ObserveDuration fb -> (P.observeDuration histogram $ runS fb)
```

which doesn't compile because there's an unhandled effect `Embed IO`. I'm a bit confused now, and I can't figure it out with the documentation itself. I see that it is a higher-order effect (hence the `interpretFinal`). The docs mention that one should use `interpretH` with `withStrategicToFinal` or `withWeavingToFinal`, maybe that's the right path here.
I also think that it's similar to the `Resource` effect that models a `bracket` wrapping an action, with the difference being that the wrapping actions are effectful themselves.

`observeDuration` has type `observeDuration :: (Observer metric, MonadIO m, MonadMonitor m) => metric -> m a -> m a` though, and I guess it should use `IO` for `m` because there are instances for `MonadIO` and `MonadMontior` for `IO` already.

The whole thing compiles without the `P.observeDuration histogram` part. I guess I have to lift the `observeDuration` into a `Sem` context?

**Comment by googleson78** [comment]
Here's something similar to what you're trying to do - https://github.com/polysemy-research/polysemy/issues/228

The reason why you're getting an "unhandled `Embed IO`" is because `Sem r` is `MonadIO` only if `Member (Embed IO) r`. So by using `observeDuration`, which has a `MonadIO` constraint, you're also getting a `Member (Embed IO) r` which you need to dispatch.

**Comment by tek** [comment]
it's not that simple. you have to bind `runS fb` before using it, since it returns a `Sem (WithStrategy m f n) (m (f a))`. However, if there's no instance of `MonadMonitor` for `Sem`, I don't see that that will work. you will have to `bindS` the `observeDuration` function first. then maybe the result must be applied to `liftS`, not sure.

**Comment by googleson78** [comment]
Actually `MonadMonitor` is simply [the same as `MonadIO`](https://github.com/qnikst/prometheus-haskell/blob/master/prometheus-client/src/Prometheus/MonadMonitor.hs#L34). I'm guessing they have some internal convention on what the difference between the two is supposed to be.

**Comment by tek** [comment]
you can see its purpose further down in the instance for `MonitorT` – they're logging every thunk with `WriterT`

**Comment by L7R7** [comment]
Nice discussion about the profiling effect! Hadn't seen that one before. I think the ideal solution for me would be to use that and write an interpretation that writes the timings into the metrics as soon as the Profiling is available in polysemy.

For now, I think I could get away with something similar to what's discussed in #228, something like this:

```hs
profileTime :: forall r a
             . Member (Embed IO) r
            => Histogram -> Sem r a
            -> Sem r a
profileTime histogram sem = do
  timeBefore <- (embedToMonadIO @IO) getMonotonicTime
  !a         <- sem
  timeAfter  <- (embedToMonadIO @IO) getMonotonicTime
  let !timeTaken = timeAfter - timeBefore
  embed (observe histogram timeTaken :: IO ())
  pure a
``` 

which does the timing "manually" and writes it to the Histogram using [`observe`](https://github.com/qnikst/prometheus-haskell/blob/master/prometheus-client/src/Prometheus/Metric/Observer.hs#L17). This uses the prometheus library only relying on the instances for `IO`, so I can avoid dealing with writing instances for `Sem r`

The idea is that I use this function in the interpreter for the `DurationObservation` effect, but I don't know yet how to combine `Embed` inside `interpretH` (or `interceptH`?)

**Comment by tek** [comment]
using `embed` in `interpretH` should be easy with `liftT` (which is `pureT <=< raise`). And using `embedToMonadIO` like that is a detour, you can just leave it out (I assume you're using a `MonadIO` variant of `getMonotonicTime`, which will be instantiated to `Sem`'s instance using `embed`.

**Comment by L7R7** [comment]
Hmm. I'm not sure I understand. My complete code for that looks like this:
```hs
observeDurationToIO :: (Member (Final IO) r) => UpdateJobDurationHistogram -> Sem (DurationObservation ': r) a -> Sem r a
observeDurationToIO histogram = interpretFinal @IO $ \case
  ObserveDuration fb -> (profileTime histogram $ runS fb)
  
profileTime :: forall r a
             . Member (Embed IO) r
            => Histogram -> Sem r a
            -> Sem r a
profileTime histogram sem = do
  timeBefore <- getMonotonicTime
  !a         <- sem
  timeAfter  <- getMonotonicTime
  let !timeTaken = timeAfter - timeBefore
  embed (observe histogram timeTaken :: IO ())
  pure a
```

which doesn't complie:
```
    • Unhandled effect 'Embed IO'
      Probable fix:
        add an interpretation for 'Embed IO'
    • In the expression: profileTime histogram
      In the expression: (profileTime histogram $ runS fb)
      In a case alternative:
          ObserveDuration fb -> (profileTime histogram $ runS fb)
   |
71 |   ObserveDuration fb -> (profileTime histogram $ runS fb)`
   |
```

The documentation for `liftT` says that it can create a first-order interpreter from a higher-order one. Wouldn't I want something the other way round, lifting into the higher-order effect I'm interpreting in `observeDurationToIO`?

**Comment by tek** [comment]
ah, you said `interpretH`. Since you're now not using a higher-order `IO` function (`P.observeDuration`) anymore, you should indeed use that instead of `interpretFinal`. Then it's probably just `liftT (profileTime histogram =<< runT fb`.

**Comment by L7R7** [comment]
Ah, my bad. With `interpretH` it's better indeed. The variant with `liftT` you proposed doesn't compile, but I found [this project](https://github.com/f-o-a-m/kepler/blob/0af053732a2ff34d7e604da618c335057fbcc31b/hs-abci-sdk/src/Tendermint/SDK/BaseApp/Metrics/Prometheus.hs#L207) which basically does what I want to achieve. With that, I came up with the following:
```hs
observeDurationToIO :: (Member (Embed IO) r) => UpdateJobDurationHistogram -> Sem (DurationObservation ': r) a -> Sem r a
observeDurationToIO histogram = interpretH $ \case
  ObserveDuration fb ->  do
    start <- getMonotonicTime
    a <- runT fb
    end <- getMonotonicTime
    let !timeTaken = end - start
    embed (observe histogram timeTaken :: IO ())
    raise $ observeDurationToIO histogram a
```
This compiles at least. I haven't tested it yet, but from what I can tell this looks fine. What do you think?

**Comment by tek** [comment]
that won't work, since the embedded thunk will only be bound in the last line. you'll have to move that to directly under `runT`.

**Comment by L7R7** [comment]
You're right. Just tested it, and the observed durations were _fast_, now I know why :smiley: 

```hs
observeDurationToIO :: (Member (Embed IO) r) => UpdateJobDurationHistogram -> Sem (DurationObservation ': r) a -> Sem r a
observeDurationToIO histogram = interpretH $ \case
  ObserveDuration fb ->  do
    start <- getMonotonicTime
    a <- runT fb
    res <- raise $ observeDurationToIO histogram a
    end <- getMonotonicTime
    let !timeTaken = end - start
    embed (observe histogram timeTaken :: IO ())
    pure res
```
With that, the results look correct.

**Comment by tek** [comment]
wonderful!

**Comment by L7R7** [comment]
I'd say this can be closed as I have a working solution now. I'll revisit this when #228 found it's way into the library.

@tek, @googleson78 , thank you very much for your help! I really appreciate that!

**Comment by tek** [comment]
great!
