### ISSUE TITLE
Dedication

### ISSUE THREAD

**Issue by yaxu** [polysemy-research/polysemy#402]
Why does the readme start with a joke about a man shooting his grandmother, written by a notorious anti-semite? It seems an unfortunately violent introduction to a library.

**Comment by KingoftheHomeless** [comment]
I don't have a problem with the joke itself. But the fact its author was anti-Semitic I don't particularly care for.
I'll remove it for the time being until the team settles on a solution.

**Comment by yaxu** [comment]
Thanks for considering this @KingoftheHomeless

**Comment by isovector** [comment]
People are so touchy these days

**Comment by yaxu** [comment]
Yes believe it or not some people even get touchy about antisemites. I heard about this one guy who got touchy about someone getting touchy about antisemites.

**Comment by KingoftheHomeless** [comment]
I'll nip this in the bud before this has the opportunity to get out of hand.
Whatever opinion you hold about the quote itself, the dedication is such a minor thing that it doesn't warrant controversy. The fact that even one person has a problem with it for reasons that are -- at the very least -- understandable, is reason enough to remove it. The old quote is gone, and it won't return unless there's enough reason for the staff to change our minds.
The issue isn't completely settled, however -- we may introduce a new quote to replace the old one. For that reason, I'm reopening this issue. If anyone has strong opinions that the old quote should stay, _privately contact Polysemy staff_. **Do not argue about it here.**
