### ISSUE TITLE
Please, can there be less active voice in the documentation

### ISSUE THREAD

**Issue by Anton-Latukha** [polysemy-research/polysemy#403]
Please:

> It allows you to separate your business logic from your implementation details. And in doing so, polysemy lets you turn your implementation code into reusable library code.

It just "triggered" me.

What if it is not only me in the project, is it applies?
How would I put `exists/forall` quantifiers on semantics?

Is `polysemy`"
> allows to separate (only) in the case of your business logic from your implementation details.(?)

Because "you" and "yours" constantly points that I am the only I one exists that can do anything, and the information does not apply forall cases.

What if business logic is not mine, or only a part of it is mine, and a part of it is Google's business logic API. If it goes through proprietary code and API Google services and result returns back - is it mine business logic?

It allows to turn only my implementation code in the library code? Or anyone code would work also, it is said only mine would be converted.
Does the code I write at Enterprisy Corp mine? No, it is not, I do not own the code I wrote, and my property rights to it were by *me, personally and explicitly* signed-off to belong to the Enterprisy Corp, so seems I should know that code is not mine.
What if I am a DevOps that deploys on a container cluster. When I sleep, and there 100 000 instances are running - is that me doing all those transformations & calculations on the other side of the Earth?

Can I smash atoms. Personally?

Please. I just started to read the introduction, and it is already tiresome. Because the real description of the values and processes right away gets intermingled with some active pronouns, and I process the language, as code also, literally as it said or written, with a connotation it is given in. So besides the information and processes, I need to imagine the virtual reality when "we", whoever "we" is exist, and choose whoever "we" group can probably consist of. We talk in a virtual class with a virtual real blackboard, the is our personal talk, someone in front of a blackboard putting a finger into me and says "you", "you Anton!.. Is it your infrastructure there?", I'm like "no, not really", at that point my mind is so vividly imagining it - it starts to wonder who is sitting in the class, what are those, and who and how much I crave, ... uff, their skirts, this one particularly... In other words, it is hard to concentrate when someone yells "You!" all the time, and if to listen to that active voice directly and literally - it creates a huge mental overhead that distracts from reading and impacts emotionally. And emotional reactions occupies the triune brain... and that is all.

`You` can/should be used only when the description of a process, really, trully involves the person and process can not be described without the person, like: "you are free to chat with us [here]", "if you took some task, let others know you're working on it".

Personalities need not to be bothered until it is truly necessary. It is not important who and what gender has and sexual preferences, the process description does not involve those.

It would've been way harder to read the math if Mac Lane explained Categories as: "the functor we talked about goes in that I previously defined C Category of mine, which is a morphism in a yours one Category G, so what happens with us if the functor gets a natural transformation?".

When describing the abstract processes it is useful to use passive voice. Just like in professional technical literature, or science literature: because they does not uses *ad hominem*, passive voice phrasing directly and clearly describes the process, it is also impossible to offend anybody, because there are personalities are not involved

**Comment by evanrelf** [comment]
I think you may be reading too deeply into the specific wording of the documentation. You're suggesting there's a lot of meaning/intent behind it, but I don't agree.

However, if you believe there's room for improvement, I'd encourage you to open a pull request with concrete suggestions for how it could be better written.

**Comment by tek** [comment]
very entertaining :stuck_out_tongue: though I'm not sure whether this is supposed to mock the previous issue or the common requests to change third person pronouns.

**Comment by kitlangton** [comment]
> _Please, use less active voice in documentation_ Please, can there be less active voice in the documentation
The rename is a work of art.

**Comment by Anton-Latukha** [comment]
Thank you.

I've just needed to transmit the information about the style.
That the active voice may be hip, but it is harder to grok than the technical description of the processes.
Of course, any style of documentation, is better than no documentation.

To contribute any meaningful documentation a deep understanding is required, so that stated are for the majority of case conditions is True.

Otherwise, the person only can contribute the form of editorial rewriting without understanding the technical context deeply. That essentially is a form of post-production and so can be seen as policing the speech. And doing editorial reviewing so that in PRs people do editorial reviewing of editorial reviewing, is not my aim.

---

And to be honest I tried to contribute the docs in the past to different projects. Let's say my exp, that with the code patch that has docs it is easy to pass PR review, but not as easy as with code without any docs to pass the PR review - no docs - nothing to critique/nitpick essentially, the hardest is to with the technical docs pass the *code-minded review process of a developer*, devs often do not understand the editorial "good enough" policy, or the Wiki process, so be prepared for a lot of nitpicking, recursive processes and holy wars of opinions.

Needless to say I stopped contributing the docs, and decided that just talking with people about it is a better strategy.

So thanks if anything was useful.

**Comment by Anton-Latukha** [comment]
> > old: _Please, use less active voice in documentation_
> > new: Please, can there be less active voice in the documentation
> 
> The rename is a work of art.

Well, the main thing, there are no *ad hominem* "you" in there, so it is less personal and without dragging people into virtual reality that the talk is direct.
Again, "Please, use less active voice in documentation" was too forceful. The "use passive voice" also not a really completely True for all 100% cases statement, because ~90%, because there are phrases and topics that indeed need active voice, and some active voice is still need here and for more emotional engagement.
