### ISSUE TITLE
Defining a web application that persists state in memory

### ISSUE THREAD

**Issue by mdimjasevic** [polysemy-research/polysemy#404]
I've been trying to implement a web game by using Polysemy. It has several effects, including an input, key-value stores (via the state effect in an in-memory map), several errors, and a random value generator. I have a final interpreter that hoists a Servant web server, but somehow I fail to persist the changes in the state between two web endpoint calls.

In particular, at the beginning there are no open games, as witnessed by an empty JSON response for `GET /sve-igre`. Then when a new game is initialised via a `POST /nova` request, via debug logging I can see the endpoint updating the state by adding the newly initialised game, however when I make a request to `GET /sve-igre` again, the response is still empty. In other words, the state is not really persisted in the memory, but gets discarded as soon as an endpoint handler finishes with its execution.

My question is: how to define a Servant web server that persists state in the memory?

Here are a few relevant links:
* The full source code: https://git.hacklab.krizevci.info/mdim/connect4 (my apologies for identifiers and comments in Croatian).
* The web server: https://git.hacklab.krizevci.info/mdim/connect4/-/blob/master/src/WebSucelje.hs#L123
* The `Application` maker function: https://git.hacklab.krizevci.info/mdim/connect4/-/blob/master/src/ImplementacijeSucelja/Aplikacija.hs#L66
* The `main` function: https://git.hacklab.krizevci.info/mdim/connect4/-/blob/master/app/Main.hs#L21

I based this implementation on a Polysemy guide available at https://github.com/thma/PolysemyCleanArchitecture.

**Comment by tek** [comment]
you're using `State`! Since endpoints are handled concurrently, you need to use `AtomicState`, which is safely storing data in a `TVar` of `IORef`.

**Comment by mdimjasevic** [comment]
@tek , I agree with your observation about concurrency. I will take a look at replacing `State` by `AtomicState`.

However, if you consider a case where I am the only user on the localhost and I can ensure that in my usage there are no concurrent requests, I would expect the state to be persisted. In other words, I believe using a state that addresses the concurrency issue (e.g., `AtomicState`) does not solve my problem of persisting at least something.

**Comment by tek** [comment]
The issue is not concurrent access, but the semantics of `State`. Servant will spawn a thread for a request regardless of how many are active, and any `State` operations done in that thread will not affect the main thread's `State`. This is a property of the underlying `StateT`.

**Comment by mdimjasevic** [comment]
> The issue is not concurrent access, but the semantics of `State`. Servant will spawn a thread for a request regardless of how many are active, and any `State` operations done in that thread will not affect the main thread's `State`. This is a property of the underlying `StateT`.

Ok, thanks!

I've noticed another analogous issue, which is with threading the seed in the pseudo-random number generator. Every new call to an endpoint results in the same initial seed used, which can be seen by always getting the same random value. How to address that?

**Comment by tek** [comment]
same issue – you'll have to copy the definition of `Random` from the zoo to your project, replacing `runState` with `runAtomicStateWithTVar`. that's what I did in a Servant project as well

**Comment by tek** [comment]
btw really hard to navigate a project written in Croatian :joy:

**Comment by mdimjasevic** [comment]
Thanks for your help again! I will try to implement these in terms of `AtomicState`.

My plan is, if I manage to pull this mini-project off, is to rewrite the code in English and then write it up as a blog post. I haven't seen many resources on combining an effects system and Servant, yet at least to me it seems non-trivial to combine the two.

**Comment by tek** [comment]
there are a few stories about Servant over in our Zulip at https://funprog.zulipchat.com , come join us!

**Comment by leomayleomay** [comment]
@tek I found it really difficult to introduce `transaction` when there's SQL queries involved, I tried to follow https://github.com/polysemy-research/polysemy/issues/23 but I found it's beyond my recognition and I can never make sense of it by reading the code :(, that's why I ditched effect system and switched back to simple Haskell

**Comment by mdimjasevic** [comment]
> there are a few stories about Servant over in our Zulip at https://funprog.zulipchat.com , come join us!

I'd love to, but where do I find the relevant stories without attempting to read everything?

**Comment by mdimjasevic** [comment]
@tek , thanks a lot for telling me about `AtomicState`! I reworked my implementation by replacing `State` with `AtomicState` and now the state is actually saved. So glad to see it working!

I'm also pleasantly surprised how little I had to change to make this happen. This just tells me the whole approach of using an effects system, thereby separating orthogonal concerns, is quite robust.

**Comment by tek** [comment]
> @tek I found it really difficult to introduce `transaction` when there's SQL queries involved, I tried to follow #23 but I found it's beyond my recognition and I can never make sense of it by reading the code :(, that's why I ditched effect system and switched back to simple Haskell

@leomayleomay yeah we're working on making tasks like that easier, see for example https://github.com/polysemy-research/polysemy-scoped

**Comment by tek** [comment]
> I'd love to, but where do I find the relevant stories without attempting to read everything?

Well there's a search function :upside_down_face: 

> I'm also pleasantly surprised how little I had to change to make this happen. This just tells me the whole approach of using an effects system, thereby separating orthogonal concerns, is quite robust.

yess! that's where polysemy really gets pleasant. awesome that it works for you now!
