### ISSUE TITLE
Signature of liftS in ghc 8.10.4 and ghc 9.0.1 with polysemy 1.5 respectivly 1.6

### ISSUE THREAD

**Issue by alaendle** [polysemy-research/polysemy#415]
Guess this is more a breaking change in GHC, nonetheless, since I recognized the changed behaviour in my code in conjunction with polysemy, I'm interested in your opinion - and maybe this feedback helps to fill a good bug report for ghc 😉 

So with GHC 9.0.1 and polysemy 1.6 ghci exposes the following type for `liftS`:
```
ghci> :t liftS
liftS :: Functor m => m a -> Strategic m n a

ghci> :t liftS $ liftIO
liftS $ liftIO
  :: (MonadIO m, Functor f) =>
     Sem (WithStrategy ((->) (IO a)) f n) (IO a -> f (m a))

ghci> :t liftS . liftIO
<interactive>:1:1: error:
    * Couldn't match type `c' with `Strategic m n a'
      Expected: m a -> c
        Actual: m a -> Strategic m n a
      `c' is a rigid type variable bound by
        the inferred type of it :: MonadIO m => IO a -> c
        at <interactive>:1:1
    * In the first argument of `(.)', namely `liftS'
      In the expression: liftS . liftIO
```

The same code in ghci 8.10.4 with polysemy 1.5:
```
ghci> :t liftS
liftS
  :: (Functor m, Functor f) =>
     m a -> Sem (WithStrategy m f n) (m (f a))

ghci> :t liftS $ liftIO
liftS $ liftIO
  :: (MonadIO m, Functor f) =>
     Sem (WithStrategy ((->) (IO a)) f n) (IO a -> f (m a))

ghci> :t liftS . liftIO
liftS . liftIO
  :: (Functor f, MonadIO m) =>
     IO a -> Sem (WithStrategy m f n) (m (f a))
```

So with GHC 9 `f . g $ x` no longer seems to be the same as `f $ g $ x`?

**Comment by KingoftheHomeless** [comment]
Type weirdness in GHC 9.0.1 is due to [the loss of function contravariance](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0287-simplify-subsumption.rst#contravariance). It has caused [some](https://github.com/polysemy-research/polysemy/pull/410#discussion_r615239214) [headaches](https://github.com/polysemy-research/polysemy-zoo/issues/69) for us.

And yes, the solution is eta-expansion . `liftS . liftIO` won't do what you want, but `(\x -> liftS $ liftIO x)` will.

**Comment by KingoftheHomeless** [comment]
Since this issue is not related to `polysemy`, I will close it. Feel free to continue discussion, but as annoying the changes to the type system are, they're easily resolved and necessary to support quick-look impredicativity, so I personally am OK with it.

**Comment by alaendle** [comment]
Thanks @KingoftheHomeless for that information - I wasn't aware of that GHC change, need to think about it for a few minutes...

I knew it was worth asking the real experts!

**Comment by alaendle** [comment]
This is really off-topic but I really find the type inference of ghc 9 confusing - because it is really counter-intuitive because eta conversion (in both directions!) is no longer only of syntactic interest. 

Out of curiosity I tried to write a linear version of `interpretFinal` (don't care if this implementation is meaningful - it's just about the types). So I have:
```
interpretFinalLinear :: forall m e r a. Member (Final m) r => (forall x rInitial. e (Sem rInitial) x %1 -> Strategic m (Sem rInitial) x) %1 -> Sem (e : r) a %1 -> Sem r a
interpretFinalLinear i = toLinear2 (\(i' :: (forall x rInitial. e (Sem rInitial) x -> Strategic m (Sem rInitial) x)) sem -> interpretFinal @m i' sem) (\sem -> i sem)
```
Writing something like this should feel easy - but the need to add these 'unnecessary' lamda's and the type annotation obscures the code - I really hope that things get more ergonomic in GHC's future (maybe this is complaining at a high level, but code like this is more about the question how to satisfy the compiler rather than the declaration of the programmers intent).

And also apologize that is misuse this issue for such a statement - but after hours of trying to solve this type puzzle I just had to get rid of that 😜

**Comment by googleson78** [comment]
> because eta conversion (in both directions!) is no longer only of syntactic interest.

I think this was not true previously either, as iirc it also affects some optimisations. (stuff like (this)[https://www.joachim-breitner.de/blog/763-Faster_Winter_5__Eta-Expanding_ReaderT] makes me suspect that it might be so)
