### ISSUE TITLE
Improve polysemy-plugin error messages

### ISSUE THREAD

**Issue by blackheaven** [polysemy-research/polysemy#417]
Following my [article](https://blog.hetchr.com/polysemy-retrospective/), I raised that the on boarding was more difficult than necessary since compilation errors are often not really relevant, for instance :

```
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# OPTIONS_GHC -fplugin=Polysemy.Plugin #-}

module Bug where

import Data.Kind
import Polysemy

data Foo (m :: Type -> Type) (a :: Type) where
  Bar :: Bool -> a -> Foo m (Maybe a)

makeSem ''Foo

prg :: Member Foo r => Sem r (Maybe ())
prg = bar True
```

Which gives:

```
Bug.hs:20:7: error:
    • Could not deduce: (Member Foo r0) 
      Fix:
        add (Member Foo r0) to the context of
          the type signature
    • In the expression: bar True
      In an equation for ‘prg’: prg = bar True
   |
20 | prg = bar True
   |       ^^^^^^^^
```

This can be surprising for newcomers, thinking that the effect is called correctly while an application is missing (and since the function declaration is missing, they cannot find a reference in the code).

I would expect something like:

```
Bug.hs:20:7: error:
    • Couldn't match expected type ‘Sem r (Maybe ())T’ with actual type ‘() -> Sem r (Maybe ())’
    • Probable cause: ‘bar’ is applied to too few arguments
       In the expression: bar True
      In an equation for ‘prg’: prg = bar True
   |
20 | prg = bar True
   |       ^^^^^^^^
```

The other bug has been reported in #363

**Comment by googleson78** [comment]
Hey, first of all, great article - thanks for the usage report!

Unfortunately, the error messages situation is non-trivial - there were attempts to make it better, and in the end, Sandy reached a conclusion that the way custom type errors work in ghc is not optimal (see #227, https://gitlab.haskell.org/ghc/ghc/issues/16906#note_221198, https://github.com/ghc-proposals/ghc-proposals/pull/278)).

This is, of course, in no way satisfactory or even helpful, but I'm hoping this will shed some light on the situation we're currently in. (I have also had/have issues with how polysemy errors sometimes hide more helpful ones.)

**Comment by isovector** [comment]
Fixed in HEAD!
