### ISSUE TITLE
Chaining monad like Either

### ISSUE THREAD

**Issue by bhoudebert** [polysemy-research/polysemy#418]
We wish to chain several `Sem r (Either a b)` with the `>>=` operator but we cannot find a way to write something nice.

Following code is garbage but could help for the discussion.

```haskell
f1 :: Int -> Sem r (Either Int String)
f1 a = f2 a >>= f3 -- do not work as the unwrap is an Either and not the "right part" obviously

f2 :: Int -> Sem r (Either Int Int)

f3 :: Int -> Sem r (Either Int String) 
```

Currently in our code we are using a lot of lift (`<-`) and manual pattern maching but I was wondering if we could do better.

**Comment by ocharles** [comment]
You could locally wrap each `f1` here with `ExceptT` - you don't have to use `polysemy` for everything :smile:

**Comment by googleson78** [comment]
Somewhat similarly, if you have a lot of `Either`s it might be worth using `Error` instead of manually passing around the values, but I have no clue about what your actual use case is.

**Comment by tek** [comment]
`runError` interprets to `ExceptT`, so it is highly likely that your code will be at least as readable if you used `throw` instead of `Left` or called `fromEither` on an `Either`!

**Comment by bhoudebert** [comment]
I will give a try, thanks for quick responding.

About more context this was arround this:

We are using polysemy from servant handler. So no real way to dodge that part (as my Either function have side effects otherwise I would not care).

```haskell 

polysemyToHandler ::
   ... ->
   Sem '[ {-- all possible effect --}] a -> Handler a
polysemyHandler ... = runM . {-- all interpreters here --}

myHandler :: Members '[Database, MyConfiguration, Log, Async, Kafka] r => -- only specific effect for sure
...
```
And the previous functions f1, f2, f3 have effect too. Example, f1 is reading configuration, f2 doing database stuff, f3 doing some kafka, all are doing log etc.

So in fact most of our functions have the Polysemy effect (of course we have some pure function but in the end not for my current use case).

There is not a lot of Either but some and from my understanding Error would cut the flow and I need to know it is an error in the handler to return for example a 400 http status.

**Comment by bhoudebert** [comment]
Okay I switch back to use throw, it works but still don't know if it is worth in my case but good to experiment, thxs.
