### ISSUE TITLE
`errorToIOFinal` potentially mixes errors up

### ISSUE THREAD

**Issue by re-xyr** [polysemy-research/polysemy#444]
As per [what Alexis King found out about `Error` interpretation in `effectful`](https://github.com/arybczak/effectful/issues/1#issuecomment-867236416), I found that `polysemy` in fact is subject to the same problem for the `errorToIOFinal` handler. Take this `Filesystem` effect:

```haskell
data Filesystem :: Effect where
  ReadFile :: FilePath -> Filesystem m String
  WriteFile :: FilePath -> String -> Filesystem m ()
makeSem ''Filesystem
```

and an interpreter:
```haskell
newtype FsError = FsError String
  deriving stock (Show)
  deriving anyclass (Exception)

runFilesystemPure :: Member (Error FsError) es => Map FilePath String -> Sem (Filesystem ': es) a -> Sem es a
runFilesystemPure fs = evalState fs . reinterpret \case
  ReadFile path -> maybeM 
    (throw $ FsError $ "File not found: " ++ show path)
    pure $ gets (M.lookup path)
  WriteFile path contents -> modify $ M.insert path contents
```

Ideally, this test would give a `Left`:

```haskell
f :: IO (Either FsError (Either FsError String))
f = runFinal $ errorToIOFinal $ runFilesystemPure M.empty $ do
  errorToIOFinal $ readFile "nonexistent"
```

because the inner `errorToIOFinal` should not be able to see the implementation of `ReadFile`. But in fact we get

```haskell
>>> f
Right (Left (FsError "File not found: \"nonexistent\""))
```

This breaks effect encapsulation in a subtle way. It should be relatively easy to fix though; Polysemy can assign `OpaqueExc`s with `Unique` IDs on each `errorToIOFinal` calls.

**Comment by KingoftheHomeless** [comment]
Oh yes, I forgot to port the `OpaqueExc` solution to Polysemy from [`in-other-words`](https://hackage.haskell.org/package/in-other-words-0.2.0.0/docs/src/Control.Effect.Internal.Error.html#OpaqueExc). As long as someone is willing to wrangle with `Strategy`, this makes for a good first issue.
