### ISSUE TITLE
Looking for a good way to copy readers to new interpreter stack

### ISSUE THREAD

**Issue by newhoggy** [polysemy-research/polysemy#449]
I have this problem:

```
liftIO $ runInApp (aFromEnv . bFromEnv . cFromEnv)
```

Where `aFromEnv`, `bFromEnv` and `cFromEnv` have the same type as `runReader a`, `runReader b` and `runReader c`.  The problem with the above code is the interpreters passed in `runInApp` are run multiple times in a tight loop and `aFromEnv`, `bFromEnv` and `cFromEnv` are expensive (a lot more than `runReader a`, `runReader b` and `runReader c`)

To fix the problem I can do this:

```
aFromEnv . bFromEnv . cFromEnv $ do
  a <- ask @A
  b <- ask @B
  c <- ask @C
  liftIO $ runInApp (runReader a . runReader b . runReader c)
```

But this is unwieldy as the list of readers becomes longer.

Is there an easy way to have the convenience of the first code, but the performance of the second?

**Comment by isovector** [comment]
I don't understand how this is related to polysemy. Some more code would help!
