### ISSUE TITLE
runTSimple fails to compile when eta-reduced

### ISSUE THREAD

**Issue by qwbarch** [polysemy-research/polysemy#454]
This is a pretty minor issue, but it's bothering me since I can't compose functions when using ``runTSimple``.
Here is an example of what compiles and what doesn't:
```haskell
import Polysemy (InterpreterFor, interpretH, makeSem, runTSimple)

data Foo m a where
  Bar :: (Int -> m a) -> Foo m ()

makeSem ''Foo

interpretFoo :: InterpreterFor Foo r
interpretFoo = interpretH $ \case
  Bar f -> do
    let getInt = pure 0
    -- this compiles
    getInt >>= \x -> runTSimple (f x)
    -- this fails to compile
    getInt >>= (runTSimple . f)
```

Any ideas on why this is happening?

**Comment by tek** [comment]
Assuming you mean `runTSimple . f`, this is certainly due to the temporary change introduced in GHC 9 and reverted in 9.2.4 called [Simplified Subsumption](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0287-simplify-subsumption.rst). There is no way around it other than upgrading GHC.

**Comment by qwbarch** [comment]
Whoops good catch, I didn't notice the missing compose function earlier.
I'm just going to bump my ghc version to avoid the change then. Thanks a lot!

**Comment by tek** [comment]
note that HLS does not work well with Polysemy on GHC 9.2 ([issue](https://github.com/haskell/haskell-language-server/issues/2989))

**Comment by qwbarch** [comment]
Hmm that's unfortunate. I'll try downgrading to 8.10.7 for now then. Thanks for pointing that out

**Comment by tek** [comment]
I think it might be easier to just eta-expand :slightly_smiling_face:

**Comment by qwbarch** [comment]
My code-base should be compatible with 8.10.7, so I might as well take the extra step to get rid of the ugliness of eta-expansions hehe
