### ISSUE TITLE
Plans to employ delimited continuations?

### ISSUE THREAD

**Issue by arrowd** [polysemy-research/polysemy#467]
GHC 9.6 gained primitive operations called delimited continuations to support building effect libraries. This feature was talked about [here](https://www.youtube.com/watch?v=0jI-AlWEwYI) and was proposed to be added to GHC [here](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0313-delimited-continuation-primops.rst).

Are there any plans to make use of delimited continuations in polysemy?

**Comment by KingoftheHomeless** [comment]
No.

There are multiple reasons why, the simplest of which is that the delimited continuation primops are IO-exclusive, and Polysemy isn't IO-based.
Another simple reason is that we have no use of them. The primops are simply meant as a performant means of capturing continuations; we have continuation capturing already thanks to the nature of free monads.

**Comment by arrowd** [comment]
Thanks, I was expecting such answer but wanted to make sure I understand it right.

But then, the video I linked claims that for Free monads to perform well its binds must be inlined. Is this the case for Polysemy?

**Comment by KingoftheHomeless** [comment]
Yup. [Polysemy's slow](https://reasonablypolymorphic.com/blog/mea-culpa/). There are a couple of things we can do to improve it, but nothing that would rival any IO-based effect system.

**Comment by arrowd** [comment]
Great, thanks for explanations!

**Comment by brandonchinn178** [comment]
Perhaps the README should be updated, then? e.g. this section seems to be outdated:

> When it comes to `polysemy`, once GHC proposal lands, we will consider the option of switching to an implementation based on it. This will probably require some breaking changes, but should resolve performance issues and maybe even make implementation of higher-order effects easier.

**Comment by ribosomerocker** [comment]
Yep, I came to this issue precisely because it seems the README's performance section is outdated now, as the continuation primops have been merged for a while now and there's no plans to use them to improve performance like it implies. @tek Sorry for mentioning you, but could this be fixed?

**Comment by tek** [comment]
good point, thanks

**Comment by ribosomerocker** [comment]
No problem. I think you've missed the "TL;DR" hyperlink in the header, though-- The section it leads to has been removed.

**Comment by tek** [comment]
oh yeah!
