### ISSUE TITLE
Async and concurrency

### ISSUE THREAD

**Issue by drlkf** [polysemy-research/polysemy#480]
What is the correct way to implement aync and concurrent computations within an effect stack ? I haven't found an obvious way since:
- `async` only allows `IO` actions, impossible to call `Sem r` actions (aside maybe from `withWeavingToFinal` given `Final IO` but that seems hacky)
- `lifted-async` requires `MonadBaseControl IO` which I've been told in #477 is unreachable with `polysemy` right now

I don't know any other library that provides something similar, what should I go for ? I'm mainly interested in `mapConcurrently`, if that narrows it down enough to have a simple solution.

**Comment by KingoftheHomeless** [comment]
As in, for `polysemy`? We have the `Async` effect -- from the `Polysemy.Async` module -- which is interpreted in terms of `Final IO`. It even offers `mapConcurrently`. It is arguably hacky -- it's certainly not perfect. It's the equivalent of using `MonadBaseControl` to lower `m a` to `IO (StM m a)` and then using a function `StM m a -> Maybe a` to transform that to `IO (Maybe a)`. A `MonadBaseControl IO` for `Sem` itself _could_ be possible, but not until the core rewrite, and even then it would have major restrictions placed upon it.

As for other effect systems, there are some purely IO-based effect systems like `cleff` and `effectful` which can offer you `MonadUnliftIO`, which `polysemy` will never do (unless a purely-IO fork is developed, which we're considering.) There are things about them I don't like -- dubious safety and correctness of implementation, `effectful`'s love of microoptimizations at significant external and internal complexity costs -- but they _are_ valid choices. `cleff` is _much_ simpler and so the one I prefer of the two, but `effectful` has some additional power, is more batteries included, and has an author that is invested in seeing it succeed. _Far too_ invested, in my opinion -- he has acted in service of his library in ways I really wish he wouldn't -- but those are only the concerns of an effect system developer. For a user, like you, it's instead a guarantee you'll receive support.
Other than that, there is also [`in-other-words`](https://hackage.haskell.org/package/in-other-words), an effect system I authored, which offers [a complete mirror of the `Async` interface through the `Conc` effect](https://hackage.haskell.org/package/in-other-words-0.2.1.1/docs/Control-Effect-Conc.html). [It is also able to pretty easily interoperate with `MonadBaseControl`.](https://hackage.haskell.org/package/in-other-words-0.2.1.1/docs/Control-Effect-BaseControl.html)
`in-other-words` is fully featured and documented, and so I'd argue isn't a bad choice (though I am of course biased) -- however, its primary aim is to have no compromises when it comes to expressive power, and sacrifices simplicity and some ergonomics to achieve that goal. So it may not align with your needs.

**Comment by drlkf** [comment]
Thank you for the comprehensive answer. I have to admit, I'm a bit reticent to the idea of completely rewriting my programs with another library for fear that I would run into an issue that would block me in a similar way and shift the problem to somewhere else in the stack. It seems that `Polysemy.Async` will do the trick just fine.
Thanks!

**Comment by arybczak** [comment]
> Far too invested, in my opinion -- he has acted in service of his library in ways I really wish he wouldn't

Would you mind expanding on this?

**Comment by arybczak** [comment]
You can write me an email.

![Screenshot_20230705_205516](https://github.com/polysemy-research/polysemy/assets/387658/1338a22c-61ab-4be0-bb39-19da4ea3c5f4)
