### ISSUE TITLE
Weird error message with no commas

### ISSUE THREAD

**Issue by ocharles** [polysemy-research/polysemy#74]
I just got:

```
    • Ambiguous use of effect 'State'
      Possible fix:
        add (Member (State FeederId) Error
                                       InsertTraydatasAndTraytypesFailure
                                       : r1) to the context of 
          the type signature
```

I think this is actually telling me to add `( Member ( State FeederId ) r, Member ( Error InsertTraydatasAndTraytypesFailure ) r)`

**Comment by jhenahan** [comment]
Can you post some sample code? I feel like I got errors like this with `Error` in my stack when I used `.` where I should have used `.@` or `.@@`.

**Comment by ocharles** [comment]
Unfortunately I've moved passed this error now and got things fixed up. I wanted to provide a repro, but was moving pretty fast. If it comes up again I'll try and narrow it down. FWIW, I didn't need to use `.@` or anything.

**Comment by TheMatten** [comment]
Looking at the implementation of error:
```hs
type AmbigousEffectMessage r e t vs =
        ( 'Text "Ambiguous use of effect '"
    ':<>: 'ShowType e
    ':<>: 'Text "'"
    ':$$: 'Text "Possible fix:"
    ':$$: 'Text "  add (Member ("
    ':<>: 'ShowType t
    ':<>: 'Text ") "
    ':<>: 'ShowType r
    ':<>: 'Text ") to the context of "
    ':$$: 'Text "    the type signature"
    ':$$: 'Text "If you already have the constraint you want, instead"
    ':$$: 'Text "  add a type application to specify"
    ':$$: 'Text "    "
    ':<>: PrettyPrint vs
    ':<>: 'Text " directly, or activate polysemy-plugin which"
    ':$$: 'Text "      can usually infer the type correctly."
        )
```
it seems like `r` was simply `InsertTraydatasAndTraytypesFailure : r1` - easy to fix by adding parens around :smile:

**Comment by isovector** [comment]
Easy to fix, but hard to do right!  What we really want is a `ShowTypePrec` that can insert parens if they're necessary, but I went down that road for a while and didn't have any luck.

**Comment by TheMatten** [comment]
Is there even some way to detect partially known list? We would like to not put parens around if it's empty or simply one variable, but we can't really detect the latter, can we?

**Comment by isovector** [comment]
^ this is why `ShowTypePrec` didn't turn out to be fruitful.

**Comment by TheMatten** [comment]
Aaah :smile:

Well, current state is technically bug - maybe we can sacrifice pretty representation for something that won't puzzle users when gone wrong, like in this case.

**Comment by isovector** [comment]
Yeah, I guess. But errors like this shouldn't really happen unless you're explicitly putting in concrete type signatures. I'm a little hesitant to uglify all error messages on the happy path, especially since it happens 90%+ of the time.

**Comment by isovector** [comment]
Crazy thought: we could add a magic type family:

```haskell
type family IsTyVar (a :: k) :: Bool where
  IsTyVar a = 'True -- or maybe this should be stuck?
```

and then use this in the error messages to branch. If we intercepted this in the plugin, we could make it do what it says on the tin, but falling back to today's behavior if the plugin isn't enabled.

**Comment by ocharles** [comment]
An equally crazy idea is to show type, then use techniques in https://kcsongor.github.io/symbol-parsing-haskell/ to see if you can find any whitespace. If so, you need to surround it in parens.

**Comment by ocharles** [comment]
If you're going to use a type family, it might be better to have `ShowWithParensIfNecessary`. If the plugin is on it can see if parens are necessary. If the plugin isn't on, just always add parens.

**Comment by ocharles** [comment]
One more idea! Maybe `Effect` should have a `NeedsParens :: Bool` associated type. `template-haskell` could figure that out.

**Comment by isovector** [comment]
Unfortunately there is no `ShowType` that produces a symbol; only a `TypeError` :( Doing it in TH is a great idea though!

**Comment by ocharles** [comment]
> Unfortunately there is no ShowType that produces a symbol 

Ah yea, and this is probably for the best :sweat_smile:

**Comment by isovector** [comment]
Wait, I don't think we can do it in TH. The problem is that the expression `e ': r` needs parens; it's not a property of the effect, it's a property of whether or not the effect row is entirely polymorphic.

**Comment by ocharles** [comment]
Can't that be solved by having something pattern match on 

```haskell
type family Whatever 
  Foo (a ': b ': c)
  Foo '[ a ]
```
?

**Comment by TheMatten** [comment]
@ocharles Type family doesn't reduce if it tries to pattern match on ambiguous type variable - it get's "stuck".

Now I'm thinking if we couldn't somehow traverse list with family that has error as some other argument, which would fire if family chokes on polymorphic "spine" - something like:

```
type family DecideError errorWithParens list where
  DecideError errorWithParens (x ': xs) = DecideError errorWithParens xs
  DecideError errorWithParens '[]     = errorWithoutParens
```

**Comment by TheMatten** [comment]
Plus we would need some special case on top for single type variables (e.g. `r`).

**Comment by TheMatten** [comment]
Try this :smile: : https://repl.it/@TheMatten/TypeParens

**Comment by TheMatten** [comment]
[Version](https://repl.it/repls/KnowledgeableWeeklyOffice) modified by kcsongor that should always work

**Comment by isovector** [comment]
I've added a test for this in #113
