### ISSUE TITLE
Hackage documentation external type links not working

### ISSUE THREAD

**Issue by Infinisil** [polysemy-research/polysemy#98]
It seems that all of the links in the hackage docs point to non-existant locations. An example would be the mention of `Monoid` in [Polysemy.Output.runFoldMapOutput](https://hackage.haskell.org/package/polysemy-0.3.0.1/docs/Polysemy-Output.html#v:runFoldMapOutput), which points to this link:

https://hackage.haskell.org/package/polysemy-0.3.0.1/base-4.12.0.0/Data-Monoid.html#t:Monoid

**Comment by isovector** [comment]
Yeah, this is a known issue that I don't know how to fix. Uploading to hackage never actually builds any documentation, so I use @ChrisPenner's great `haddock-up` tool that uploads my local haddocks.

**Comment by ocharles** [comment]
There shouldn't be any reason to manually upload documentation for this library - that's for cases where you have things like C dependencies, so the Hackage server can't build it. There is `cabal upload --documentation` now - maybe give that a try?

**Comment by Infinisil** [comment]
> I use @ChrisPenner's great `haddock-up` tool that uploads my local haddocks.

I can't find this tool online, do you have a link?

In any case I think it's worth giving `cabal upload --documentation` a shot. Or alternatively, the [Hackage upload page](https://hackage.haskell.org/upload) has a note at the bottom on how to upload docs.

**Comment by isovector** [comment]
@Infinisil https://github.com/ChrisPenner/dotfiles/blob/master/bin/haddock-up

**Comment by isovector** [comment]
Maybe I just need the `--for-hackage` flag

**Comment by Infinisil** [comment]
It seems that this doesn't pass neither `--for-hackage` nor `--haddock-option=--hyperlinked-source` as mentioned in the page I linked. This very much seems like it would be the culprit.

**Comment by isovector** [comment]
Stack doesn't seem to honor `--for-hackage`. If you can figure out how to make it do that, I'd be much obliged!

**Comment by Infinisil** [comment]
Well I just wanted to test this myself but apparently stack is having some issues right now which I'm running into: https://github.com/commercialhaskell/stack/issues/3731

That said, according to https://stackoverflow.com/a/41431924/6605742, one is supposed to use `stack sdist` and `stack upload` for uploading to hackage, which you could try once stack is fixed.

Also, it seems that `stack haddock` passes the hyperlinked-source flag by default:
```
$ stack haddock --help
...
  --[no-]haddock-hyperlink-source
                           Enable/disable building hyperlinked source for
                           Haddock (like haddock --hyperlinked-source) (default:
                           enabled)
```

And I also found this flag which you could use to pass `--for-hackage`:
```
  --haddock-arguments HADDOCK_ARGS
                           Arguments passed to the haddock program
```

But maybe also not, because `--for-hackage` doesn't appear to be a haddock flag (I can't find it in haddock's source), but a Cabal one, but after looking through the source code I'm not even sure what that does.

Ugh this is annoying.

**Comment by ocharles** [comment]
I've mentioned before but it really should just be a case of doing `cabal upload -d --publish`, that's it. I know you're all `stack` users, but maybe dropping down to `cabal` is acceptable here.

**Comment by isovector** [comment]
So I just let hackage build the haddocks for `type-errors`, and it went fine. Maybe I should just be more patient with `polysemy` and everything will be fine.

**Comment by isovector** [comment]
This will be fixed on the next push to hackage, so I'm going to close it now!
